Phobos-developers/Phobos

- src/replace_shp_shadow_check.cpp
SHP debris now has their hardcoded shadows controlled by `Shadow` flag (defaults to `no`).
> Added replace_shp_shadow_check hook (not tested)

- Phobos.vcxproj
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- src/Ext/TechnoType/Hook.cpp
Allow the mind controller to have the upper limit of the control distance. Greater than 0 will activate this feature.
In rulesmd.ini:
[SOMETECHNO]            ; TechnoType
MindControlRangeLimit=-1.0 ; double
> Mind Control Range Limit

- README.md
- src/Ext/WarheadType/Body.cpp
- src/Ext/WarheadType/Body.h
- src/Ext/WarheadType/Hooks.cpp
- src/Ext/WarheadType/Serialize.hpp
Warhead with Conventional=yes sinks and causes a water splash instead of detonating when it hits water. In original game, [CombatDamage] SplashList= specifies a list of animations the game will use for this case. An animation is chosen depending on the Damage of the warhead's weapon by dividing this damage by 35, then rounding down to an integer to form a zero-based index.
Now any WarheadType can specify what animations to use for this case.
In rulesmd.ini
[SOMEWH] ; WarheadType
SplashList= ; list of animations, a random animation from the list to play if EMEffect=yes
; otherwise playing rules are same as original
; if no valid anim is listed, default rules will be applied here.
> Allow SplashList set for a certain WarheadType

- src/Phobos.cpp
(probably, not sure) For preventing cheating the debug commands activation variable is declared inside rulesmd.ini and not in ra2md.ini that is modificable for everyone.
Same Ares behavior:
· [GlobalControls] -> DebugKeysEnabled doesn't exists means enabled feature.
· [GlobalControls] -> DebugKeysEnabled=yes means enabled tehse commands.
· [GlobalControls] -> DebugKeysEnabled=no means disable these commands.
> Read the debug activation variable from rulesmd.ini -> [GlobalControls] -> DebugKeysEnabled

- src/Ext/WarheadType/Hooks.cpp
> RemoveMindControl will no longer crashes when target is permanently controlled.

- src/Ext/Techno/Body.h
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- src/Ext/TechnoType/Hooks.cpp
Already spawned aircrafts from a structure in the original YR ignores the structure powered=yes value and continue attacking the target.
Powered.KillSpawns=<bool> ; default "false" for original YR experience
This tag reset the structure selected target for fix the mentioned bug and additionally kill all the flying spawns.
> Powered Spawner structure able to Kill Spawns if low power

- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- src/Ext/TechnoType/Hooks.cpp
Added 2 new Techno tags:
Spawner.LimitRange=no
Spawner.ExtraLimitRange=0
If a spawner object has Spawner.LimitRange=yes
The spawned unit will abort the infinite pursuit it had in original YR until it ran out of ammo when the enemy is out of range.
Additionally, Spawner.ExtraLimitRange adds extra pursuit range to the spawned units.
> New Spawns Limit Range

- Phobos.vcxproj
- docs/User-Interface.md
- src/Misc/Hooks.Blowfish.cpp
Fixed error `***FATAL*** String Manager failed to initilaized properly`, which occurred if `Blowfish.dll` could not be registered in the OS, for example, it happened when the player did not have administrator rights. With Phobos, if the game did not find a registered file in the system, it will no longer try to register this file, but will loading it bypassing registration. 
Screenshot of a bug in a vanilla game:
> Fix loader blowfish.dll

- src/Phobos.cpp
The [GlobalControls]->DebugKeysEnabled value was ignored by the game
> DebugKeysEnabled Fix

- Phobos.vcxproj
- docs/Fixed-or-Improved-Logics.md
- src/Ext/TerrainType/Body.cpp
- src/Ext/TerrainType/Body.h
- src/Ext/TerrainType/Hooks.cpp
- src/Utilities/GeneralUtils.cpp
- src/Utilities/GeneralUtils.h
- Allows to specify which type of tiberium this TerrainType would generate.
```ini
[SOMETERRAINTYPE]      ; TerrainType
SpawnsTiberium.Type=0  ; Tiberium type index
```
> Customizable drill ore types

- README.md
- docs/New-or-Enhanced-Logics.md
- src/Ext/WarheadType/Body.cpp
- src/Ext/WarheadType/Body.h
- src/Misc/Shield.cpp
Currently, this adds two new keys to warheads for interaction with shield logic, and tweaks the documentation to mention functionality that was not previously mentioned.
The new warhead keys:
- `PenetratesShield` allows the warhead ignore the shield and always deal full damage to the TechnoType itself. It also allows targeting the TechnoType even if weapons using the warhead cannot target or damage the shield.
- `BreaksShield` allows the warhead to always break shields of TechnoTypes, regardless of the amount of strength the shield has remaining or the damage dealt, assuming it affects the shield's armor type. Residual damage, if there is any, still respects `Shield.AbsorbOverDamage`.
> Shield logic additions / improvements

- Phobos.vcxproj
- docs/Miscellanous.md
- src/Misc/Hooks.INIClass.cpp
It is very inconvenient to use CLSID for set Locomotor. This PR adds aliases for CLSID
| *Alias*| *CLSID*                                  |
| -----: | :--------------------------------------: |
Drive    | `{4A582741-9839-11d1-B709-00A024DDAFD1}` |
Jumpjet  | `{92612C46-F71F-11d1-AC9F-006008055BB5}` |
Hover    | `{4A582742-9839-11d1-B709-00A024DDAFD1}` |
Rocket   | `{B7B49766-E576-11d3-9BD9-00104B972FE8}` |
Tunnel   | `{4A582743-9839-11d1-B709-00A024DDAFD1}` |
Walk     | `{4A582744-9839-11d1-B709-00A024DDAFD1}` |
DropPod  | `{4A582745-9839-11d1-B709-00A024DDAFD1}` |
Fly      | `{4A582746-9839-11d1-B709-00A024DDAFD1}` |
Teleport | `{4A582747-9839-11d1-B709-00A024DDAFD1}` |
Mech     | `{55D141B8-DB94-11d1-AC98-006008055BB5}` |
Ship     | `{2BEA74E1-7CCA-11d3-BE14-00104B62A16C}` |
> Semantic values ​​for the Locomotor tag

- .editorconfig
- README.md
- docs/New-or-Enhanced-Logics.md
- src/Ext/Techno/Body.cpp
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
Adding `Interceptor.GuardRange`, `Interceptor.EliteGuardRange`, `Interceptor.MinimumGuardRange` and `Interceptor.EliteMinimumGuardRange`
> Improvements & minimum guard range for interceptor logic 

- docs/New-or-Enhanced-Logics.md
- src/Ext/Techno/Body.h
- src/Ext/Techno/Hooks.Shield.cpp
- src/Misc/Shield.cpp
- src/Misc/Shield.h
- src/Utilities/GeneralUtils.cpp
- src/Utilities/GeneralUtils.h
Fix the known bug during shield implementation
> Shield logic improvements

- docs/Fixed-or-Improved-Logics.md
- src/Ext/Script/Hooks.cpp
This  possibly fix the Script Action 4 Move to cell from calculating the cell from dividing 128 to 1000.
> Possible fix buggy MoveToCell which uses 128 as leftovers

- docs/User-Interface.md
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/Misc/Hooks.PCX.cpp
- src/Misc/Hooks.UI.cpp
This feature allows to custom missing cameo with any shp/pcx file. When using a PCX as XXICON, we don't need to change `cameo.pal` to extend colors for the cameo anymore. This feature is standalone, i.e. don't need Ares to work
```ini
[AudioVisual]
MissingCameo=XXICON.SHP   ; filename
```
> Allow to customize missing cameo

- README.md
- docs/Fixed-or-Improved-Logics.md
- src/Ext/TechnoType/Hooks.cpp
- src/Misc/Hooks.BugFixes.cpp
- Explicitly use weapon specified by `DeployFireWeapon` for firing deploy weapon.
- Respect `FireOnce` setting on the weapon.
- Respect stop commands issued during firing the deploy weapon.
If I am not mistaken this addresses #112.
> Vehicle DeployFire improvements / fixes

- Phobos.vcxproj
- README.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/TAction/Body.cpp
- src/Ext/TAction/Body.h
- src/Ext/TAction/Hooks.cpp
- src/Phobos.Ext.cpp
In vanilla YR, TActionClass::CreateBuildingAt's implement skipped the BuildUp animation and thus you will see buildings suddenly appear from nothing. This fix plays the animation.
> Map trigger action 125 Build at will play BuildUp animation now.

- src/Ext/Techno/Hooks.Shield.cpp
- src/New/Entity/Shield.h
When infantry garrisoned building or unit entered transport, the shield will be removed because game called pThis->Remove(). Just removing the hook won't cause other side effect but losing anim after this action. So kill anim here
> Fix the bug about shield removing when garrison/enter something

- Phobos.vcxproj
- README.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/Unit/Hooks.DisallowMoving.cpp
Makes `Speed=0` vehicles stationary (basically behave like deployed `IsSimpleDeployer=true` vehicles). Shouldn't be used on buildable vehicles, as they won't be able to exit factories.
Closes #5.
> Stationary vehicles (pseudo-IsSimpleDeployer)

- Phobos.vcxproj
- README.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/AnimType/Body.cpp
- src/Ext/AnimType/Body.h
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- src/Ext/TechnoType/Hooks.cpp
- src/Phobos.Ext.cpp
- You can now specify which anim should be drawn when harvester gathering each type of ores.
```ini
[SOMEHARVESTER]             ; Harvester
OreGath.Anims=              ; list of animations
OreGath.FramesPerDir=15     ; list of integers
OreGath.TiberiumTypes=      ; list of TiberiumType IDs, if not set, always display the first
```
For example:
```ini
[CMIN]
...
OreGath.Anims=NUKEANIM,OREGATH
OreGath.TiberiumTypes=112,30
OreGath.FramesPerDir=1,2
...
```
`NUKEANIM` will be played while the chrono miner is gathering normal golds
`OREGATH(the default anim)` will be played while the chrono miner is gathering gems
> Cusomizable Harvester Oregath Animation

- README.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- src/Ext/TechnoType/Hooks.cpp
Allows to make TechnoTypes unable to be ordered with a movement command.
```ini
[SOMETECHO]      ; TechnoType
NoManualMove=no  ; boolean
```
Closes #5.
> NoManualMove tag for TechnoTypes

- docs/Fixed-or-Improved-Logics.md
- src/Misc/Hooks.BugFixes.cpp
`Naval` won't affect `WaterBound` at all
closes #232
> Skip Naval check on WaterBound

- README.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/Misc/Hooks.BugFixes.cpp
Re-enable obsolete [JumpjetControls], the keys in it will be as the default value of jumpjet units.
Moreover, added two tags for missing ones.
In `rulesmd.ini`: 
```ini
[JumpjetControls]
Crash=5.0       ; float
NoWabbles=no    ; bool
```
Note: `CruiseHeight` is for `JumpjetHeight`, `WobblesPerSecond` is for `JumpjetWobbles`, `WobbleDeviation` is for `JumpjetDeviation`, and `Acceleration` is for `JumpjetAccel`. All other corresponding keys just simply have no `Jumpjet` prefix.
> Re-enable obsolete [JumpjetControls]

- README.md
- docs/Fixed-or-Improved-Logics.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/Techno/Body.cpp
- src/Ext/Techno/Body.h
- src/Ext/Techno/Hooks.cpp
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- src/Ext/WeaponType/Body.cpp
- src/Ext/WeaponType/Body.h
- src/Misc/Hooks.BugFixes.cpp
- You can now specify separate firing offsets for each of the shots fired by weapon with `Burst` via using `(Elite)PrimaryFire|SecondaryFire|WeaponX|FLH.BurstN` keys, depending on which weapons your TechnoType makes use of. *N* in `BurstN` is zero-based burst shot index, and the values are parsed sequentially until no value for either regular or elite weapon is present, with elite weapon defaulting to regular weapon FLH if only it is missing. If no burst-index specific value is available, value from the base key (f.ex `PrimaryFireFLH`) is used.
- Burst-index specific firing offsets are absolute firing offsets and the lateral shifting based on burst index that occurs with the base firing offsets is not applied.
```ini
[SOMETECHNO]                   ; TechnoType Image …
```
> Burst logic improvements / additions

- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/BuildingType/Hooks.Upgrade.cpp
- src/Ext/Bullet/Body.cpp
- src/Ext/Bullet/Hook.cpp
- src/Ext/RadSite/Body.cpp
- src/Ext/RadSite/Body.h
- src/Ext/RadSite/Hooks.cpp
- src/Ext/TAction/Hooks.cpp
- src/Ext/Techno/Body.cpp
- src/Ext/Techno/Body.h
- src/Ext/Techno/Hooks.cpp
- src/Ext/WarheadType/Body.cpp
- src/Ext/WarheadType/Detonate.cpp
- src/Ext/WarheadType/Hooks.cpp
- src/Misc/Hooks.UI.cpp
- src/Phobos.version.h
Phobos fixes:
- Fixed random crashes about CameoPriority (by Uranusian)
- Fixed trigger action 125 not functioning properly (by Uranusian)
- Fixed area warhead detonation not falling back to firer house (by Otamaa)
- RadSite hook adjustment for `FootClass` to support Ares `RadImmune`; also various fixes to radiation / desolators (by Otamaa)
- Fixed `Crit.Affects` not functioning properly (by Uranusian)
- Fixed improper upgrade owner transfer which resulted in built ally / enemy building upgrades keeping the player who built them alive (by Kerbiter)
> Hotfix v0.2.2.1

- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/Ext/Script/Body.cpp
- src/Ext/Script/Body.h
These use a new [AITargetType] section in rulesmd.ini for finding a specific enemy target.
Backported from PR 296 and I know that this was tested by Ayylmao because some some people these actions makes the enemy selection very flexible
> Script Actions 84-91: Mission attack that use a list of possible targets

- README.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/Script/Body.cpp
- src/Ext/Script/Body.h
Action 92 backported from PR 296
Executed BEFORE the attack script action you wanted to affect it sets how many attempts will do the affected action before acorting the action and jump to the next script line.
If set n=0 then the Team always stays waiting for a valid target in the attack action.
The effect ends when the attack action picked a target.
Old YR AI actions can't use this feature.Action 92 backported from PR 296
In `aimd.ini`:
[SOMESCRIPTTYPE]  ; ScriptType
x=92,n            ; integer n=0
> Script Action 92: Wait If No Target Found

- README.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/Script/Body.cpp
- src/Ext/Script/Body.h
Script Action 93 backported from PR 296
When executed before a new Attack ScriptType Actions like `74-81` and `84-91` the TeamType will remember that must be rewarded increasing the current Weight of the AI Trigger when the TeamType Target was killed by any of the Team members. The current Weight will never surprass the Minimum Weight and Maximum Weight limits of the AI Trigger. The second parameter is a positive value. 
Only affects the first (new) attack script action ran after this action.
In `aimd.ini`:
[SOMESCRIPTTYPE]  ; ScriptType
x=93,n            ; integer n=0
> Script Action 93: Team's Trigger Weight Reward

- README.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/Ext/Script/Body.cpp
- src/Ext/Script/Body.h
Script Action 94 Backported from PR 296.
When executed it picks a random Script Type and replaces the current script by the new picked.
The second parameter is a 0-based index for the [AIScriptsList] section that specifies the list of possible [ScriptTypes] that can be evaluated. The new [AIScriptsList] section must be declared in RulesMD.ini for making this script work:
[AIScriptsList] ; List of ScriptTypes
0=ScriptType N,ScriptType N+1, ScriptType N+1,... ScriptType N+M
1= ...
2= ...
...
> Script Action 94: Pick Random Script

- README.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/Techno/Hooks.cpp
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- You can now make TechnoType automatically fire its weapon(s) without having to scan for suitable targets by setting `AutoFire`, on either its base cell (in which case the weapon that is used for force-firing is used) or itself (in which case normal targeting and weapon selection rules and are respected) depending on if `AutoFire.TargetSelf` is set or not.
```ini
[SOMETECHNO]            ; TechnoType
AutoFire=no             ; boolean
AutoFire.TargetSelf=no  ; boolean
```
Primary use-case is passive things like shield /  cloak generators, some dummy object weapons etc. that don't need an actual target. Full-map threat scanning is potentially *very* detrimental to performance if map is large and filled to brim with objects, hence the need to find alternate solutions. As a …
> Implement AutoFire for TechnoTypes

- Phobos.vcxproj
- README.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/Building/Body.cpp
- src/Ext/Building/Body.h
- src/Ext/House/Body.cpp
- src/Ext/House/Body.h
- src/Ext/SWType/Body.cpp
- src/Ext/SWType/Body.h
- src/Ext/SWType/FireSuperWeapon.cpp
- src/Ext/SWType/Hooks.cpp
- src/Utilities/GeneralUtils.cpp
- src/Utilities/GeneralUtils.h
You can now, through Super Weapons, deliver BuildingTypes that will appear "in limbo" instead of the game world. These buildings will satisfy prerequisite checks, grant Super Weapons, supply or drain power, and generally act as if they existed (cannot be factories or have weapons, or generally contain any mechanics that require them to have coordinates). These buildings can be removed from "limbo" with LimboKill superweapons, that erase all buildings with matching IDs.
Documentation copy below.
- Super Weapons can now deliver off-map buildings that act as if they were on the field.
- `LimboDelivery.Types` is the list of BuildingTypes that will be created when the Super Weapons fire. Super Weapon Type and coordinates do not matter.
- `LimboDelivery.IDs` is the list of numeric IDs that will …
> LimboDelivery

- README.md
- docs/New-or-Enhanced-Logics.md
- src/Ext/AnimType/Body.cpp
- src/Ext/AnimType/Body.h
- src/Ext/AnimType/Hooks.AnimCreateUnit.cpp
- `CreateUnit.ConsiderPathfinding`, if set, makes game look for eligible cells around the animation's coordinates if the cell at those coordinates is not passable to the created unit, and creates the unit at the first eligible cell found instead.
- Warhead `AnimList/SplashList` animations and animations created through map trigger action `41 Play Anim At` now have owner set correctly if the animation has `CreateUnit` set.
> CreateUnit improvements

- Phobos.vcxproj
- README.md
- docs/Fixed-or-Improved-Logics.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Misc/Hooks.Image.cpp
- src/Phobos.cpp
- src/Phobos.h
`Image` tag in artmd.ini previously was available only for BuildingTypes and AnimationTypes. Now it is possible to use it for InfantryTypes, VXL & SHP VehicleTypes and AircraftTypes. Usage is the same as with BuildingTypes/AnimationTypes.
**By default this feature is disabled to remain compatible with YR. To use this feature, enable it in rules with `ArtImageSwap=true`.
```ini
[General]
NoArtImageSwap=false   ; default to false, original logic
```
```ini
[SOMETECHNO]
Image=                 ; name of the file that will be used as image, without extension
```
> Make Image work for InfantryTypes, VehicleTypes and AircraftTypes in artmd.ini

- README.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/AnimType/Body.cpp
- src/Ext/AnimType/Body.h
- src/Ext/AnimType/Hooks.cpp
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- src/Ext/TechnoType/Hooks.cpp
- You can now customize whether or not animations attached to objects follow the object's layer or respect their own `Layer` setting. If this is unset, attached animations use `ground` layer.
```ini
[SOMEANIM]                 ; AnimationType
Layer.UseObjectLayer=      ; boolean
```
Allows turning on or off jumpjet unit behaviour where they fluctuate between `air` and `top` layers based on whether or not their current altitude is equal / below or above `JumpjetHeight` or `[JumpjetControls] -> CruiseHeight` if former is not set on TechnoType. If disabled, airborne jumpjet units exists only in `air` layer. `JumpjetAllowLayerDeviation` defaults to value of `[JumpjetControls] -> AllowLayerDeviation` if not specified.
```ini
[JumpjetControls] …
```
> Animation & Jumpjet unit layer customization

- docs/New-or-Enhanced-Logics.md
- src/Ext/Techno/Hooks.cpp
- src/Ext/WarheadType/Hooks.cpp
- src/Utilities/EnumFunctions.cpp
- src/Utilities/EnumFunctions.h
- `CanTarget` now explicitly requires `all` or `empty` to be listed to be able to fire at cells containing no TechnoTypes.
- `AreaFire.Target=base` & `AreaFire.Target=self` (when firing the weapon, not for targeting or weapons selection) weapons are exempt from this.
- `AreaFire.Target=random` now respects `CanTargetHouses`.
- Fixed an issue where `AreaFire.Target=self` would override the firing techno's current target with itself.
Uses cases include changing force-fire weapon from Primary to Secondary (which can even be done conditionally based on whether cell is land or water) and allowing `AreaFire.Target=random` weapons to home into (specific) objects (owned by specific houses) instead of always allowing empty cells to be targeted.
> Weapon targeting filter improvements

- README.md
- docs/Fixed-or-Improved-Logics.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/Techno/Hooks.Shield.cpp
- src/Ext/Techno/Hooks.cpp
- src/Ext/WarheadType/Body.cpp
- src/Ext/WarheadType/Body.h
- src/Ext/WarheadType/Detonate.cpp
- src/New/Entity/ShieldClass.cpp
- src/New/Entity/ShieldClass.h
- src/New/Type/ShieldTypeClass.cpp
- src/New/Type/ShieldTypeClass.h
- Fixed a number of issues with shields interacting with TechnoType changes (Undeploys/DeploysInto, Ares type conversion). If new TechnoType has `ShieldType` set, that shield will always be used, otherwise new `ShieldType` setting `AllowTransfer` determines if the (old) shield carries over or not. If `AllowTransfer` is not set, it defaults to `true` if shield was created through Warhead `Shield.AttachTypes`, otherwise `false`.
- Cloaked objects with shields are now uncloaked if the shield gets damaged by a warhead.
- Introduced a new Warhead setting `DecloakDamagedTargets`, which controls whether or not the warhead will decloak targets if it damages them (this applies to both shielded and unshielded targets. Defaults to `true`.
- Negative shield self-healing will now work as expected, …
> Shield / misc. fixes & improvements

- src/Misc/Hooks.UI.cpp
Reported [here](https://ppmforums.com/topic-55634-page-5/phobos-project-ares-compatible-yr-engine-expansion).
> Hotfix: Fix the counter having incorrect color when drain > 0 and output == 0

- src/Ext/Script/Body.cpp
Some tweaks in the new Attack function and helper function for picking a valid target
> Small tweaks in the new Attack script action

- src/Ext/Techno/Body.cpp
- src/Ext/Techno/Body.h
PassengerDeletion.Rate did not work properly.
> Fix issue 474

- src/Ext/Techno/Hooks.cpp
Convert.Deploy is an Ares tag so is necessary an extra check for loading the right Laser Trails when the unit is transformed.
> Update Laser Trails after Convert.Deploy transformation

- src/Ext/TerrainType/Body.cpp
- src/Ext/TerrainType/Body.h
- src/Ext/TerrainType/Hooks.cpp
These Features doesnt work on tiberium tree , due to how game coded it , blame WWP !
`Rules.ini`
```
[SOMETREE]
DestroyAnim = ; AnimType
DestroySound= ; Sound
```
> Some simple addition to Terrain type 

- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Misc/Hooks.BugFixes.cpp
This makes crashable jumpjet units crash if they are destroyed while affected by `Locomotor` warhead, instead of simply falling to ground (and not dying at all due to Phobos fixes to prevent units counting as dying multiple times while crashing etc).
> Make jumpjets crash correctly if killed while pulled by Locomotor WH

- src/Ext/Techno/Hooks.cpp
- Fix: Units garrisoned inside Opentopped units generated LaserTrails.
- Fix: A LaserTrailer line is generated between the original location the units had when entered into the transport and the location when they left the transport.
> Lasertrails fixes when units enter/leave transports

- docs/Fixed-or-Improved-Logics.md
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- src/Ext/TechnoType/Hooks.cpp
This is to remove parsing conflicts with Ares, due to Ares treating any other facing than 0-8 as invalid when parsing INI content and thus generating warnings such as:
`[Developer warning]Failed to parse INI file content: [ATCRT]DeployDir=-1 (Expected a facing between 0 and 8)`
Besides requiring INI changes, no actual functionality should have been lost with this change. This will still only apply to ground units due to the Ares hook for jumpjet unit DeployDir being at an address that can't be hooked around.
Translated documentation will need to be adjusted to match the changes here.
> Replace DeployDir customization with DeployingAnim.AllowAnyDirection

- README.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/AnimType/Body.cpp
- src/Ext/AnimType/Body.h
- src/Ext/AnimType/Hooks.cpp
- You can now customize whether or not animations attached to objects are centered at the object's actual center rather than the bottom of their top-leftmost cell (cell #0).
```ini
[SOMEANIM]                       ; AnimationType
UseCenterCoordsIfAttached=false  ; boolean
```
The effect is most noticeable on buildings larger than 1x1, but even on 1x1 buildings and units it will shift the animation up half a cell (15 pixels or so).
> Allow centering attached anims on object center

- src/Ext/Script/Body.cpp
In Attack and Move script actions.
Instead of mention only the current line now show the line, Action and argument and in few cases who was the Team Leader.
> Extra info in debug lines

- src/Ext/Building/Body.cpp
- src/Ext/Building/Body.h
- src/Ext/BuildingType/Body.cpp
- src/Ext/BuildingType/Body.h
- src/Ext/Techno/Hooks.Grinding.cpp
- Fix PerCellProcess hook conflicts with Ares
- Move CanGrindTechno from BuildingTypeExt to BuildingExt
- Move PerCellProcess hook code to a function in BuildingExt to reduce redundancy
Closes #554
> Refactor & fix grinding code

- docs/New-or-Enhanced-Logics.md
- src/Ext/WarheadType/Body.cpp
- src/Ext/WarheadType/Body.h
- src/Ext/WarheadType/Detonate.cpp
- src/New/Entity/ShieldClass.cpp
- src/New/Entity/ShieldClass.h
- src/New/Type/ShieldTypeClass.cpp
- Allocate `BreakWeapon` if not found to prevent potential problems parsing the weapon if not listed in WeaponTypes (and possibly even if it is) and for consistency
- Add `Shield.MinimumReplaceDelay` on Warheads that controls how long after shield was broken can it be replaced if `Shield.ReplaceNonRespawning` is set. Primary use-case would be to balance out things like shield generators etc. so that they won't immediately restore shields after they have been broken.
- Fix to negative self-healing not starting on `Powered=false` shields unless damaged.
Closes #571
> Small shield improvements / additions

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Techno/Hooks.cpp
- src/Ext/WeaponType/Body.cpp
- src/Ext/WeaponType/Body.h
- src/Misc/Hooks.LaserDraw.cpp
- src/Utilities/GeneralUtils.cpp
- src/Utilities/GeneralUtils.h
- You can now set laser to draw using only `LaserInnerColor` by setting `IsSingleColor`, in same manner as `IsHouseColor` lasers do using player's team color. These lasers respect laser thickness.
```ini
[SOMEWEAPON]         ; WeaponType
IsSingleColor=false  ; boolean
```
Additionally, fixed single-color laser (IsHouseColor, IsSingleColor, LaserTrails) laser glow falloff to match the vanilla appearance.
*In order from left to right: original game behaviour, the old Phobos behaviour, new Phobos behaviour.*
**NOTE:** This change will affect appearance of existing laser trails, modders may need to review their settings / values.
Closes #410
> Single-color lasers (that respect thickness) & laser glow improvements

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Techno/Body.cpp
- src/Ext/Techno/Body.h
- src/Ext/Techno/Hooks.cpp
Game deletes mind control animations when cloaking objects, but doesn't restore them on uncloak. This fixes that, and should function with any types of mind control animation (regular, Dominator and Ares PermaControl warheads).
> Fix mind control indicator animations not reappearing on uncloak

- Phobos.vcxproj
- README.md
- docs/Fixed-or-Improved-Logics.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/Bullet/Body.cpp
- src/Ext/Bullet/Body.h
- src/Ext/Bullet/Hooks.cpp
- src/Ext/Bullet/Trajectories/BombardTrajectory.cpp
- src/Ext/Bullet/Trajectories/BombardTrajectory.h
- src/Ext/Bullet/Trajectories/PhobosTrajectory.cpp
- src/Ext/Bullet/Trajectories/PhobosTrajectory.h
- src/Ext/Bullet/Trajectories/SampleTrajectory.cpp
- src/Ext/Bullet/Trajectories/SampleTrajectory.h
- src/Ext/Bullet/Trajectories/StraightTrajectory.cpp
- src/Ext/Bullet/Trajectories/StraightTrajectory.h
- src/Ext/BulletType/Body.cpp
- src/Ext/BulletType/Body.h
- src/Ext/WeaponType/Body.cpp
- src/Ext/WeaponType/Body.h
This is rebased & reopened version of [secsome's original PR](https://github.com/Phobos-developers/Phobos/pull/432).
- Projectiles can now have customizable trajectories.
- `Trajectory` should not be combined with original game's projectile trajectory logics (`Arcing`, `ROT` or `Inviso`).
- Self-explanatory, is a straight-shot trajectory.
- Initial speed is determined by weapon's `Trajectory.Speed`.
```ini
[SOMEPROJECTILE]     ; Projectile
Trajectory=Straight  ; Trajectory type
```
- Similar trajectory to `Straight`, but targets a coordinate above the intended target (height determined by `Trajectory.Bombard.Height`). When the projectile approaches that coordinate, it will free fall and explodes when it hits the target or ground.
- Initial speed is determined by weapon's …
> Custom projectile trajectories

- docs/New-or-Enhanced-Logics.md
- src/Ext/Techno/Body.cpp
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- Objects can be destroyed automatically under certaing cases:
- No Ammo: The object will die if the remaining ammo reaches 0.
- Countdown: The object will die if the countdown reaches 0.
- **Peaceful: If `NoAmmo` or `Countdown` is set, the object will be removed from the game peacefully, without triggering DeathWeapon or "Unit lost" EVA.**
```ini
[SOMETECHNO]                       ; TechnoType
Death.NoAmmo=no                    ; boolean
Death.Countdown=0                  ; integer
Death.Peaceful=no                  ; boolean, default to no
```
Someone asked me how to commit a PR, I didn't remember. So, a random commit just for testing
> Unit auto-death enhancement: allow peaceful removal from the game

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/Ext/Techno/Body.cpp
- src/Ext/Techno/Body.h
- src/Ext/Techno/Hooks.cpp
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- Allows jumpjet units to face towards the target when firing from different directions. Set `[JumpjetControls] -> FacingTarget=yes` to enable it for all jumpjet locomotor units. This behavior can be overriden by setting `[UnitType] -> JumpjetFacingTarget` for specific units.
- This behavior does not apply to `TurretSpins=yes` units for obvious reasons.
```ini
[JumpjetControls]
FacingTarget=no        ; boolean
[UnitType]
JumpjetFacingTarget=   ; boolean, override the tag in JumpjetControls
Locomotor=Jumpjet      ; Jumpjet only
TurretSpins=no         ; It's meaningless to use that for disks obviously
```
> Jumpjet facing bugfix: Jumpjet units face towards target when firing from different directions

- CREDITS.md
- Phobos.vcxproj
- docs/Fixed-or-Improved-Logics.md
- docs/Miscellanous.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Commands/Commands.cpp
- src/Commands/DamageDisplay.h
- src/Ext/Building/Body.cpp
- src/Ext/Building/Body.h
- src/Ext/Building/Hooks.cpp
- src/Ext/BuildingType/Body.cpp
- src/Ext/BuildingType/Body.h
- src/Ext/Techno/Body.cpp
- src/Ext/Techno/Body.h
- src/Ext/Techno/Hooks.cpp
- src/Ext/WarheadType/Body.cpp
- src/Ext/WarheadType/Body.h
- src/Ext/WarheadType/Detonate.cpp
- src/Misc/FlyingStrings.cpp
- src/Misc/FlyingStrings.h
- src/Misc/Hooks.UI.cpp
- src/New/Entity/ShieldClass.cpp
- src/Phobos.cpp
- src/Phobos.h
FlyingStrings implementation based on the original [Ares implementation](https://github.com/Ares-Developers/Ares/blob/596cb2103f9f1677ae2cb06084a4a0fbbf27c503/src/Misc/FlyingStrings.h) by AlexB & Joshy, modified by otamaa and Starkku.
`Grinding.DisplayRefund` can be set to display the amount of credits acquired upon grinding on the building. Multiple refunded objects within a short period of time have their refund amounts coalesced into single display.
- `Grinding.DisplayRefund.Houses` determines which houses can see the credits display.
- `Grinding.DisplayRefund.Offset` is additional pixel offset for the center of the credits display, by default (0,0) at building's center.
```ini
[SOMEBUILDING]                     ; BuildingType
Grinding.DisplayRefund=false       ; …
```
> FlyingStrings / TransactMoney.Display / Grinding.DisplayRefund / Display damage hotkey command

- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/New/Entity/ShieldClass.cpp
- src/New/Entity/ShieldClass.h
- src/New/Type/ShieldTypeClass.cpp
- src/New/Type/ShieldTypeClass.h
- src/Utilities/GeneralUtils.cpp
- src/Utilities/GeneralUtils.h
- src/Utilities/Template.h
- src/Utilities/TemplateDef.h
Added damage-state specific shield idle animations.
In `rulesmd.ini`: (Only new keys shown)
```ini
[SOMESHIELDTYPE]                   ; ShieldType name
IdleAnim.ConditionYellow=          ; animation
IdleAnim.ConditionRed=             ; animation
IdleAnimDamaged=                   ; animation
IdleAnimDamaged.ConditionYellow=   ; animation
IdleAnimDamaged.ConditionRed=      ; animation
```
An excerpt from adjusted documentation for shield idle animations:
- `IdleAnim`, if set, will be played while the shield is intact. This animation is automatically set to loop indefinitely.
- `IdleAnim.ConditionYellow` and `IdleAnim.ConditionRed` can be used to set different animations for when shield health is at or below the percentage defined in `[AudioVisual]`->`ConditionYellow`/`ConditionRed`, …
> Shield animation & pip customizations

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/Ext/Techno/Body.cpp
- src/Ext/Techno/Body.h
- src/Ext/Techno/Hooks.cpp
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- src/Misc/Hooks.BugFixes.cpp
- src/Utilities/Enum.h
- src/Utilities/TemplateDef.h
- It is now possible to set a global cap for the effects of `InfantryGainSelfHeal` and `UnitsGainSelfHeal` by setting `InfantryGainSelfHealCap` & `UnitsGainSelfHealCap` under `[General], respectively.
- It is also possible to change the pip frames displayed from `pips.shp` individually for infantry, units and buildings by setting the frames for infantry & unit self-healing on `Pips.SelfHeal.Infantry/Units/Buildings` under `[AudioVisual]`, respectively.
- Whether or not a TechnoType benefits from effects of `InfantryGainSelfHeal` or `UnitsGainSelfHeal` buildings or neither can now be controlled by setting `SelfHealGainType`.
- If `SelfHealGainType` is not set, InfantryTypes and VehicleTypes with `Organic` set to true gain self-healing from `InfantryGainSelfHeal`, other VehicleTypes from …
> Building-provided self-healing customization

- CREDITS.md
- Phobos.vcxproj
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/TerrainType/Body.cpp
- src/Ext/TerrainType/Body.h
- src/Ext/TerrainType/Hooks.Passable.cpp
- src/Ext/TerrainType/Hooks.cpp
- TerrainTypes can now be made passable or buildable upon by setting `IsPassable` or `CanBeBuiltOn`, respectively.
- Movement cursor is displayed on `IsPassable` TerrainTypes unless force-firing.
- `CanBeBuiltOn=true` terrain objects are removed when building is placed on them.
```ini
[SOMETERRAINTYPE]   ; TerrainType
IsPassable=false    ; boolean
CanBeBuiltOn=false  ; boolean
```
> Implement passable & buildable-upon TerrainTypes

- CREDITS.md
- Phobos.vcxproj
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/Techno/Body.cpp
- src/Ext/Techno/Body.h
- src/Ext/Techno/Hooks.Transport.cpp
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- Transports with `Passengers.SyncOwner` set to true will have the owner of their passengers changed to match the transport if transport's owner changes.
- On `OpenTopped=true` transports this will also disable checks that prevent target acquisition by passengers when the transport is temporarily mind controlled.
- `Passengers.SyncOwner.RevertOnExit`, if set to true, changes the passengers' owner back to whatever it was originally when they entered the transport when they are ejected.
```ini
[SOMETECHNO]                             ; TechnoType
Passengers.SyncOwner=false               ; boolean
Passengers.SyncOwner.RevertOnExit=false  ; boolean
```
> Toggle for automatic passenger owner change to match transport

- docs/User-Interface.md
- docs/locale/zh_CN/LC_MESSAGES/User-Interface.po
In the Beginning, I thought the mistake was in codes, so the Doc is right. But after my trial, it is the doc's mistake. “TXT_QUICKSAVE” works, but “TXT_QUICKGAME” not.
> Correct a Mistake in Doc

- CREDITS.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- docs/locale/zh_CN/LC_MESSAGES/New-or-Enhanced-Logics.po
- src/Ext/SWType/Body.cpp
- src/Ext/SWType/Body.h
- src/Ext/SWType/FireSuperWeapon.cpp
- src/Ext/Script/Body.cpp
- src/Ext/TechnoType/Body.h
- src/Ext/WarheadType/Body.cpp
- src/Ext/WarheadType/Body.h
- src/Ext/WarheadType/Detonate.cpp
Reopened the PR for nightly builds for testers
- Superweapons can be launched when a standard warhead is detonated. This means that animation weapons from _Ares_ are **not** supported.(even when working together with Starkku's animation damage re-implementation) Nevertheless, animation warheads may works in certain circumstances. Due to the nature of some superweapon types, not all superweapons are suitable for launch. The user should not abuse this feature.
- `LaunchSW` specifies the superweapons to launch when the warhead is detonated.
- `LaunchSW.RealLaunch` controls whether the owner who fired the warhead must own all listed superweapons and sufficient fund to support `Money.Amout`. Otherwise they will be launched out of nowhere.
- `LaunchSW.IgnoreInhibitors` ignores `SW.Inhibitors` …
> Launch superweapons using warhead

- src/Ext/Techno/Body.cpp
- src/Ext/Techno/Body.h
- src/Ext/Techno/Hooks.VehicleToBuildingMCFix.cpp
- src/Ext/Techno/Hooks.cpp
**This is the exact same thing as my previous "Jumpjet facing target" pull request, with a different implementation.
It won't check if the jumpjet is stationary or not.**
**Need comparison tests**
Description of the previous PR:
- Allows jumpjet units to face towards the target when firing from different directions. Set `[JumpjetControls] -> TurnToTarget=yes` to enable it for all jumpjet locomotor units. This behavior can be overriden by setting `[UnitType] -> JumpjetTurnToTarget` for specific units.
- This behavior does not apply to `TurretSpins=yes` units for obvious reasons.
```ini
[JumpjetControls]
TurnToTarget=no        ; boolean
[SOMEUNITTYPE]         ; UnitType with jumpjet locomotor
JumpjetTurnToTarget=   ; boolean, override the tag in JumpjetControls
```
> Another implementation on turning jumpjet to its target

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Aircraft/Hooks.cpp
- src/Ext/Anim/Body.cpp
- src/Ext/Anim/Body.h
- src/Ext/AnimType/Body.cpp
- src/Ext/AnimType/Body.h
- src/Ext/AnimType/Hooks.AnimCreateUnit.cpp
- src/Ext/AnimType/Hooks.cpp
- src/Ext/Building/Hooks.cpp
- src/Ext/Bullet/Hooks.cpp
- src/Ext/WarheadType/Body.cpp
- src/Ext/WarheadType/Body.h
- src/Ext/WarheadType/Hooks.cpp
- src/Ext/WeaponType/Body.cpp
- src/Ext/WeaponType/Body.h
This reimplements animation `Weapon` and `Damage.Delay` from Ares and adds ability to customize whether or not the Damage is dealt by the owner or invoker of the animation (does not affect which House is used to deal damage if `Warhead` is used, but does affect experience gain). `Weapon` is also automatically allocated and does not require explicit listing on `[WeaponTypes]`.
---------------------------
- `Weapon` can be set to a WeaponType, to create a projectile and immediately detonate it instead of simply dealing `Damage` by `Warhead`. This allows weapon effects to be applied.
- `Damage.Delay` determines delay between two applications of `Damage`. Requires `Damage` to be set to 1.0 or above. Value of 0 disables the delay. Keep in mind that this is measured in animation frames, not …
> Reimplemented animation damage / weapon /w improvements

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/TEvent/Body.cpp
- src/Ext/TEvent/Body.h
- src/Ext/TEvent/Hooks.cpp
- src/Ext/Team/Body.h
- src/Ext/Techno/Body.h
- src/Ext/TerrainType/Hooks.cpp
- src/New/Entity/ShieldClass.h
`IsAnimated`, `AnimationRate` and `AnimationProbability` now work on TerrainTypes without `SpawnsTiberium` set to true.
For a refresher, `AnimationRate` is how many game frames it takes to increment one animation frame and `AnimationProbability` is a probability (0.0 to 1.0) that animation sequence starts playing if it already is not, checked at every game frame (set to 1.0 for constant loop).
> Animated TerrainTypes

- docs/AI-Scripting-and-Mapping.md
- docs/Whats-New.md
- src/Ext/Script/Body.cpp
Like Timed Area Guard (script action 71) it now use seconds in the argument.
Is more easy to use "15" for 15 seconds than "225" for the same seconds.
> Changed Forced Jump timer from frames to ingame seconds

- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/RadSite/Hooks.cpp
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
Basically a performance-optimizing measure to prevent game from executing radiation code, wholly or partially on every game frame if it is not needed, as in majority of cases custom radiation types are either absent or use same application delays. It can be toggled off if radtype-specific delays are needed.
-------
By default `UseGlobalRadApplicationDelay` is set to true. This makes game always use `RadApplicationDelay` and `RadApplicationDelay.Building` from `[Radiation]` rather than specific radiation types. This is a performance-optimizing measure that should be disabled if a radiation type declares different application delay.
```ini
[Radiation]
UseGlobalRadApplicationDelay=true  ; boolean
```
> Implement UseGlobalRadApplicationDelay

- src/Misc/CaptureManager.cpp
Resolves #731 
Restores #675
Issue: #532 Shouldn't be merged at the beginning.
@secsome How can a building move???
Note: neither #532 nor #380 can solve #314, even this PR cannot. #675 can but it's too annoying to be accepted as an alternative.
> [Hotfix][Urgent] Fix MindControlled building cannot fire normally

- src/Ext/Techno/Body.cpp
- src/Ext/Techno/Hooks.cpp
Fixed a parameter misuse from vanilla: when YR kills a slave it used `ignoreDefense=false` rather than true. Slaves may not always get killed
> [Hotfix] Fix slaves not always dying from suicide option when slave-miner gets killed

- CREDITS.md
- docs/Whats-New.md
- src/Commands/NextIdleHarvester.h
- src/Ext/Anim/Body.cpp
- src/Ext/House/Body.cpp
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/Ext/Techno/Body.cpp
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- src/Misc/Hooks.UI.cpp
Detached from #723 ,  restore #628 , closes #603 
* Consider non-selected guarding state as harvesting miner (can subject to change, Needs review from @Metadorius @Thrifinesma ). Returning chronominers will stop blinking the counter.
* Deprecate `TechnoTypeExt::ExtData::IsCountedAsHarvester` and merged the entire logic into `Harverster.Counted` in order to improve performance. Minor refactored related harvester-counter code.
* Add a static array of TechnoTypeClasses that are considered to be `Harvester.Counted=yes` to avoid loop through all technotypes every frame.
* Do not display harvester counter or power delta for defeated players
> Refactor Harvester counter to improve performance

- CREDITS.md
- docs/Whats-New.md
- src/Ext/Techno/Body.h
- src/New/Entity/ShieldClass.cpp
- src/New/Entity/ShieldClass.h
- src/Phobos.Ext.cpp
Given the importance and the difficulty of this task, I detached this part from #721 
Prior to this PR, `ContainerMap.Find` and `InvalidatePointerHelper::Process<TechnoExt>` are the 2 major factors that greatly impact the performance, causing a significant FPS drop when objects number surpasses hundreds. 
This PR aims to detach the shield `IdleAnim` pointer invalidation from `TechnoExt` by nullifying the existing pointer invalidation virtual function of `TechnoExt::ExtData` and introducing a static one inside `ShieldClass`. So I used a global vector storing all shield class pointers. As for pointer invalidation, it loops through the vector to see if any `IdleAnim` matches.
> Performance refactor: Detach shield anim pointer invalidation from techno

- CREDITS.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/Building/Hooks.cpp
- src/Ext/House/Body.h
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/Ext/SWType/Body.cpp
- src/Ext/SWType/Body.h
- src/Ext/SWType/FireSuperWeapon.cpp
- src/Ext/SWType/Hooks.cpp
- src/Ext/Techno/Body.cpp
- src/Ext/Techno/Body.h
- src/Ext/Techno/Hooks.cpp
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- src/Ext/WarheadType/Body.cpp
- src/Ext/WarheadType/Body.h
- src/Ext/WarheadType/Detonate.cpp
- src/Phobos.cpp
- src/Phobos.h
I accidentally deleted #720, this PR restores it.
```ini
[SOMEWARHEAD]                    ; Warhead
LaunchSW.IgnoreDesignators=true  ; boolean
```
Detached shield pointer invalidation part into #740 
1. Fix the wrong hook size and stack offset for future usage of SW cell coordinates in `SuperClass::Launch` hook. Minor refactored limbo delivery part to improve the readability of #379 
2. **Moved all ForbidParalleAIlQueue related settings to `RulesExt`** #638 , serialized all related items as well as `[GlobalControls]->AllowParallelAIQueues` , fixed related code errors
> Add IgnoreDesignator option for LaunchSW, Refactor ParallelAIQueue & SWTypeExt;

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/TechnoType/Hooks.cpp
- src/Ext/Unit/Hooks.Jumpjet.cpp
Just as the title said.
BTW the bug of turreted jumpjet units always facing the bottom-right direction when not targeting anything is fixed too in #738, welcome to test them together. Only `Jumpjet=yes` units are considered.
Note:
My idb is very poor, and I can only assume at this moment that `JumpjetLocomotionClass::State` is an enum, where
* 0 - On the ground
* 1 - Taking off from the ground
* 2 - Hovering in the air
* 3 - Moving in air
* 4 - Deploying to land
* 5 - Crashing
* 6 - Unknown, probably related to crashing
It seems that `ObjectClass::UpdatePosition` is called in `4`, but not the others. I decided to add it in 3, but I'm not sure if it's also done elsewhere so I limited it to `Sensors=yes` types only for now.
Since there's something else processed in this function so there …
> Fix jumpjets' Sensors being unable to detect cloaked objects (temporarily)

- CREDITS.md
- Phobos.vcxproj
- docs/User-Interface.md
- docs/Whats-New.md
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/Ext/Side/Body.cpp
- src/Ext/Side/Body.h
- src/Ext/Surface/Body.cpp
- src/Ext/Surface/Body.h
- src/Misc/PhobosToolTip.cpp
- src/Phobos.cpp
- src/Phobos.h
```ini
[SOMESIDE]
ToolTip.Background.Color=0,0,0      ; integer - R,G,B, defaults to [AudioVisual]->ToolTip.Background.Color
ToolTip.Background.Opacity=100      ; integer, ranged in [0, 100], defaults to [AudioVisual]->ToolTip.Background.Opacity
ToolTip.Background.BlurSize=0.0     ; float, defaults to [AudioVisual]->ToolTip.Background.BlurSize
```
Ready for test.
> Customizable Tooltip background

- src/Ext/Techno/Body.cpp
It is just a display bug.
before:
after:
> Fix organic units wrongly show unit self heal pip

- CREDITS.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/Building/Body.cpp
- src/Ext/Building/Body.h
- src/Ext/BuildingType/Body.cpp
- src/Ext/BuildingType/Body.h
- src/Ext/SWType/Body.cpp
- src/Ext/SWType/Body.h
- src/Ext/SWType/FireSuperWeapon.cpp
GenericWarhead SW substitute (that works in tandem with any SW type) with proper support for all weapon / warhead features.
Code for the feature itself is pretty simple, however proper support for determining which building fired the SW required porting over large amount of helper functions from Ares 0.A though. As a result the weapon / warhead is considered to be fired by the building that fired the SW, which supports `SW.RangeMinimum/Maximum` etc (same as GenericWarhead SW).
-------------
- Any superweapon can now detonate a Warhead or a weapon at superweapon's target cell.
- If both `Detonate.Warhead` and `Detonate.Weapon` are set, latter takes precedence.
- `Detonate.Damage`, if not set, defaults to weapon ´Damage` for `Detonate.Weapon` and 0 for `Detonate.Warhead`.
- Both the weapon …
> Warhead / weapon detonation at superweapon target cell

- CREDITS.md
- docs/AI-Scripting-and-Mapping.md
- docs/Whats-New.md
- src/Ext/House/Body.cpp
- src/Ext/House/Body.h
- src/Ext/House/Hooks.cpp
- src/Ext/TAction/Hooks.cpp
Sorry I accidentally deleted #711 
In singleplayer campaigns, base nodes cannot auto-repair, neither can buildings delivered from trigger action 125 or Ares' UnitDelivery SW. This PR aims to fix this:
In your `campaign.map`:
```ini
[Country House]
RepairBaseNodes=no,no,no ; 3 booleans indicating whether AI should repair produced structures in Easy/ Normal/ Difficult game diffculty.
```
If set to `yes` at the corresponding difficulty level, the corresponding **house** will be able to repair base node structures.
For trigger action 125, note `Param3` and `Param4` from
```ini
[Actions]
...
ACTIONID=COUNT,...,125,10,BuildingTypeID,Param3,Param4,0,0,WaypointID,...
...
```
If `Param3=1`, the buildup will be played. If `Param4=1`, the building will be repairable for AI in SP missions.
> Dehardcode SP campaign AI's ability of auto-repairing structures built from base nodes / trigger action 125/ SW delivery

- CREDITS.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/SWType/Body.cpp
- src/Ext/SWType/Body.h
- src/Ext/SWType/FireSuperWeapon.cpp
- src/Ext/SWType/Hooks.cpp
- src/Ext/WarheadType/Detonate.cpp
Superweapons can now launch other superweapons at the same target. Launched types can be additionally randomized using the same rules as with LimboDelivery (see above).
- `SW.Next.RealLaunch` controls whether the owner who fired the initial superweapon must own all listed superweapons and sufficient funds to support `Money.Amout`. Otherwise they will be launched forcibly.
- `SW.Next.IgnoreInhibitors` ignores `SW.Inhibitors`/`SW.AnyInhibitor` of each superweapon, otherwise only non-inhibited superweapons are launched.
- `SW.Next.IgnoreDesignators` ignores `SW.Designators`/`SW.AnyDesignator` respectively.
```ini
[SOMESW]                        ; Super Weapon
SW.Next=                        ; List of Super Weapons
SW.Next.RealLaunch=true         ; boolean …
```
> Super Weapons launching Super Weapons, SWTypeExt improvements

- CREDITS.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/Building/Body.cpp
- src/Ext/Building/Body.h
- src/Ext/Building/Hooks.cpp
- src/Ext/BuildingType/Body.cpp
- src/Ext/BuildingType/Body.h
- Additional espionage bonuses can be toggled with `SpyEffects.Custom`.
- `SpyEffects.VictimSuperWeapon` instantly launches a Super Weapon for the owner of the infiltrated building at building's coordinates.
- `SpyEffects.InfiltratorSuperWeapon` behaves the same as above, with the Super Weapon's owner being the owner of the spying unit.
```ini
[SOMEBUILDING]                     ; BuildingType
SpyEffects.Custom=false            ; boolean
SpyEffects.VictimSuperWeapon=      ; SuperWeaponType
SpyEffects.InfiltratorSuperWeapon= ; SuperWeaponType
```
```{warning}
The following Super Weapon types are supported:
`Type=LightningStorm`                     NO
`Type=MultiMissile`                       NO
`Type=PsychicDominator`                   NO
`Type=ChronoSphere` …
```
> Custom SpyEffects

- src/Ext/Script/Body.cpp
- src/Ext/Techno/Body.cpp
- src/Ext/Techno/Body.h
- "Move to" actions set for using the end mode 0 (the one that ends the action when the Team leader reaches the destination) ended as soon as the subterranean transport traveled underground. For the action it was like if the transport wasn't in the map.
- Some Subterranean transports moved on the surface instead of using subterranean tunnels.
> Fix subterranean transports in "Move To..." script actions

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/User-Interface.md
- docs/Whats-New.md
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/Ext/Side/Body.cpp
- src/Ext/Side/Body.h
- src/Misc/Hooks.UI.cpp
- src/Phobos.cpp
- src/Phobos.h
- src/Utilities/EnumFunctions.cpp
In vanilla game, when the player selects a defense building, the radial indicator is shown only if it belongs to the player. Now the indicator is also drawn for observers. For other houses it can be specified by
```ini
[AudioVisual]
RadialIndicatorVisibility=allies  ; list of Affected House Enumeration (allies/ally | enemies/enemy | all)
```
When your power is sabotaged by a spy, the number given by the power delta counter may look confusing to players. Now I replaced it by ⚡❌, which can also be replaced by
In `uimd.ini`
```ini
[ToolTips]
PowerBlackoutLabel=  ; CSF entry key
```
If `[GlobalControls]->DebugKeysEnabled=yes` power delta is still displayed
> RadialIndicator visible to observer/allies & Different PowerDelta label when power sabotaged

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Techno/Body.h
- src/Ext/Techno/Hooks.Firing.cpp
- src/Ext/Techno/Hooks.cpp
> Allow UnitTypes to use `AlternateFLH` in opentopped transport

- CREDITS.md
- docs/AI-Scripting-and-Mapping.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Building/Body.cpp
- src/Ext/Building/Body.h
- src/Ext/Building/Hooks.cpp
- src/Ext/BuildingType/Hooks.cpp
- src/Ext/House/Hooks.cpp
`[SOMEBUILDING]->NaturalParticleSystem` creates smoke particles when a building is built and placed. However it was also played for those already placed structures in the map files, which make the intro of a campaign visually strange since those buildings should not be considered to be built on the scene by players.
This PR adds a check for all buildings to see if it's preplaced on the map file, and if yes, skip the particle creation process
This PR also fixes a similar issue for AI-Structure repairability introduced by #722 but broken by d451f0194458c370af3a34a8e0c1710f10b2ba95
Must be merged before b34
> Skip `NaturalParticleSystem` displaying from in-map pre-placed structures

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/BuildingType/Body.cpp
- src/Ext/BuildingType/Body.h
- src/Ext/Techno/Hooks.Grinding.cpp
When an infantry/unit enters a grinder, the `DieSound`/`VoiceDie` are always played.
You can now disable that per grinder
```ini
[SOMEBUILDING]
Grinding.PlayDieSound=yes
```
Can merge this only after v0.3 being merged into develop
> Allow `DieSound/VoiceDie` not being played when being grinded

- src/Ext/Bullet/Body.cpp
- src/Ext/RadSite/Body.cpp
- src/Ext/RadSite/Body.h
- src/Ext/RadSite/Hooks.cpp
- src/Ext/Techno/Body.cpp
- src/Ext/TechnoType/Body.cpp
- src/Ext/WarheadType/Detonate.cpp
- src/Utilities/Container.h
I don't think using `DynamicVectorClass` is a good idea.
This removes the `Array` from `RadExt`
and should make it simpler and perhaps faster for something like
```cpp
for( auto pObj : *SomeClass::Array)
{
auto pExt = SomeExt::ExtMap.Find(pObj);
```
by using
```cpp
for(auto& [pObj, pExt] : SomeExt::ExtMap)
```
I'm not familiar with STL yet so need help on the format
Need testing if everything else such as Radiation or Interceptor work as usual
> [Minor] Make ExtMap iterable

- src/Ext/House/Body.cpp
- src/Ext/House/Body.h
- src/Ext/House/Hooks.cpp
- src/Ext/SWType/FireSuperWeapon.cpp
Fixes an issue where buildings brought into the game via LimboDelivery are considered by AI when calculating its base center. Normally it checks if they are alive and not in limbo, but this check is satisfied by LimboDelivery buildings, so an additional check is required. For this purpose houses now keep track of LimboDelivered buildings they own (a map of BuildingExt::ExtData with AbstractClass->UniqueID as key, ExtData because it saves iterating BuildingClass array and calling ExtMap::Find on LimboKill).
> Fix LimboDelivery buildings counting in AI base center calculations

- CREDITS.md
- README.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/Misc/Hooks.BugFixes.cpp
This should fix the theoretical flaw of #809 
A histogram proving a more uniform distribution will be uploaded later
The game uses [rejection sampling](https://en.wikipedia.org/wiki/Rejection_sampling) for the random generation of crates.
- You can now limit the crates' spawn region to land only.
```ini
[CrateRules]
CrateOnlyOnLand=no  ; boolean
```
> The option to limit random crate generation only on land + sampling mechanism fix

- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/Techno/Body.cpp
- src/Ext/Techno/Body.h
- src/Ext/Techno/Hooks.cpp
- src/Ext/WeaponType/Body.cpp
- src/Ext/WeaponType/Body.h
- `Burst.FireWithinSequence` is only used if the weapon is fired by InfantryTypes, and setting it to true allows infantry to fire multiple `Burst` shots within same firing sequence.
- First shot is always fired at sequence frame determined by firing frame controls on InfantryType image (`FireUp` et al).
- Following shots come at intervals determined by `Burst.Delays` (with minimum delay of 1 frame) or random delay between 3 to 5 frames if not defined. Note that if next shot would be fired at a frame that is beyond the firing sequence's length, burst shot count is reset and weapon starts reloading.
- Burst shot counter is not immediately reset if firing is ceased mid-sequence after at least one shot, but the frame at which each burst shot is fired will not be influenced by this (in other …
> Multiple Burst shots during same infantry firing sequence

- CREDITS.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/Anim/Body.cpp
- src/Ext/Anim/Body.h
- src/Ext/Anim/Hooks.cpp
- src/Ext/AnimType/Body.cpp
- src/Ext/AnimType/Body.h
Basically `VoxelAnims` / projectile (Ares) `AttachedSystem` but for animations. Primary use case is to use for debris instead of animation trailers but there may be potential for other things too I suppose.
----
- It is now possible to attach a particle system to an animation. Only particle systems with `BehavesLike=Smoke` are supported. This works similarly to the identically named key on `VoxelAnims`.
- On animations with `Next`, the particle system will be deleted when the next animation starts playing and new one created in its stead if the `Next` animation defines a different particle system.
```ini
[SOMEANIM]       ; AnimationType
AttachedSystem=  ; ParticleSystem
```
> Attached particle system for animations

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/Techno/Body.cpp
- src/Ext/Techno/Body.h
- src/Ext/Techno/Hooks.Firing.cpp
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- If both `Primary` and `Secondary` weapons can fire at air targets (projectile has `AA=true`), `Primary` can now be picked instead of always forcing `Secondary`. Also applies to `IsGattling=true`, with odd-numbered and even-numbered `WeaponX` slots instead of `Primary` and `Secondary`, respectively.
- `IsGattling=true` can now fall back to ´secondary´ weapon slot (even-numbered `WeaponX` slots) if 'primary' one (odd-numbered) cannot fire at current target (armor type, `CanTarget(Houses)`, shield etc).
This allows for things like AA-only units with two different weapons and units using gattling logic with two sets of weapons that can both fire at ground targets.
As a bonus threw these fixes in:
- Fixed `LandTargeting=1` not preventing from targeting TerrainTypes (trees etc.) on land.
- …
> Remove hardcoded AA/Gattling weapon selection restrictions

- CREDITS.md
- Phobos.vcxproj
- docs/Fixed-or-Improved-Logics.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/Bullet/Hooks.Obstacles.cpp
- src/Ext/Bullet/Hooks.cpp
- src/Ext/BulletType/Body.cpp
- src/Ext/BulletType/Body.h
Additional obstacle logic for projectiles.
- Weapons with projectiles with `Level=true` now consider targets behind obstacles that cause the projectile to detonate (tiles belonging to non-water tilesets) as out of range and will attempt to reposition before firing.
- It is now possible to make projectiles consider either land or water as obstacles that block their path by setting `SubjectToLand/Water` to true, respectively. Weapons firing such projectiles will consider targets blocked by such obstacles as out of range and will attempt to reposition themselves so they can fire without being blocked by the said obstacles before firing and if `SubjectToLand/Water.Detonate` is set to true, the projectiles will detonate if they somehow manage to collide with the said obstacles.
- In a special …
> Projectile obstacle logic additions

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- src/Ext/Unit/Hooks.Jumpjet.cpp
- src/Ext/WeaponType/Body.cpp
- src/Ext/WeaponType/Body.h
Basically: 
**No additional tags needed** since it was actually a bug
besides, according to @Metadorius 's suggestion
Recommended for jumpjets' omnifiring weapons
```ini
[SOMEWEAPON]                ; WeaponType
OmniFire=yes                      ; condition
OmniFire.TurnToTarget=no  ; boolean
```
This should finally close the concern starting from 
#215 
#443 
#608 
#626
#639 
#738 
#744 
There were 2 causes of the bug: 
1. When jumpjets arrived at their `FootClass::Destination`, they seem stuck at the Move mission, and this pointer is not nullified unlike other locomotors. This prevents the body facing from changing in most cases
2.  Jumpjets use the facing in its loco instead of techno, no synchronization was implemented
**Warning for DP-Kratos users**: You should …
> JumpjetTurnToTarget: The correct fix, and OmniFire.TurnToTarget

- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/House/Body.cpp
- src/Ext/House/Body.h
- src/Ext/House/Hooks.cpp
- src/Ext/SWType/FireSuperWeapon.cpp
- src/Ext/Techno/Body.cpp
- src/Ext/Techno/Body.h
This allows LimboDeliver-ed buildings to use AutoDeath logic
> `AutoDeath` logic support for limboed objects

- CREDITS.md
- Phobos.vcxproj
- docs/User-Interface.md
- docs/Whats-New.md
- src/Misc/Hooks.Timers.cpp
- src/Misc/PhobosToolTip.cpp
- src/Phobos.cpp
- src/Phobos.h
- Timers can now display values in real time, taking game speed into account. This can be enabled with `RealTimeTimers=yes`.
- By default, time is calculated relative to desired framerate. Enabling `RealTimeTimers.Adaptive=yes` (always on for unlimited FPS) will calculate time relative to *current* FPS, accounting for lag.
- When playing with unlimited FPS (or custom speed above 60 FPS), the timers might constantly change value because of the unstable nature.
- This option respects custom game speeds.
- This behavior is designed to be toggleable by users. For now you can only do that externally via client or manually.
In `ra2md.ini`:
```ini
[Phobos]
RealTimeTimers=no           ; boolean
RealTimeTimers.Adaptive=no  ; boolean
```
> Real time timers

- CREDITS.md
- Phobos.vcxproj
- docs/Miscellanous.md
- docs/User-Interface.md
- docs/Whats-New.md
- docs/_static/js/ini-block-maker.js
- docs/_templates/layout.html
- src/Misc/Hooks.Gamespeed.cpp
- src/Misc/Hooks.Timers.cpp
- src/Misc/PhobosToolTip.cpp
- src/Phobos.cpp
- src/Phobos.h
Additional reference: https://docs.google.com/spreadsheets/d/1LjHrYXjXZ7vyQSYEno5hEY0VY9XhncPFlXKlWsVaM5k/edit?usp=sharing
- It is now possible to change the default (GS4/Fast/30FPS) campaign game speed with `CampaignDefaultGameSpeed`.
- It is now possible to change the *values* of single player game speed, by inputing a pair of values. This feature must be enabled with `CustomGS=true`. **Only values between 10 and 60 FPS can be consistently achieved.**
- Custom game speed is achieved by periodically manipulating the delay between game frames, thus increasing or decreasing FPS.
- `CustomGSN.ChangeInterval` describes the frame interval between applying the effect. A value of 2 means "every other frame", 3 means "every 3 frames" etc. Increase of speedup/slowdown is approximately …
> Custom single player game speed

- src/Ext/Script/Body.cpp
- If there are no transports in the vector it shouldn't continue and jump to the next mission.
- Removed the increment of current script line execution because it skips the next script line and the game will run the "next+1" instead.
> Fix some details in the transport script action code

- CREDITS.md
- Phobos.vcxproj
- docs/Miscellanous.md
- docs/Whats-New.md
- src/Misc/Hooks.INIInheritance.cpp
- INI files can now include other files (merge them into self) using `[$Include]` section.
- `[$Include]` section contains a list of files to read and include. Files can be directly in the Red Alert 2 directory or in a loaded MIX file.
- Files will be added in the same order they are defined. Index of each file **must be unique among all included files**.
- Inclusion can be nested recursively (included files can include files further). Recursion is depth-first (before including next file, check if the current one includes anything).
- When the same entry exists in two files, then the one read later will overwrite the value.
- This feature can be used in *any* INI file, be it `rulesmd.ini`, `artmd.ini`, `soundmd.ini` or others.
```{warning}
When Phobos is present, the [Ares equivalent of …
```
> WIP Reimplement INI inheritance

- CREDITS.md
- Phobos.vcxproj
- docs/AI-Scripting-and-Mapping.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Building/Body.cpp
- src/Ext/Building/Body.h
- src/Ext/Building/Hooks.Grinding.cpp
- src/Ext/Building/Hooks.Refinery.cpp
- src/Ext/Building/Hooks.Selling.cpp
- src/Ext/Scenario/Body.cpp
- src/Ext/TAction/Body.cpp
- src/Ext/TAction/Body.h
You can now set 
```ini
[Basic]
MCVRedeploys=yes
```
within your *singleplayer campaign* **map file** to allow it
(already in develop, only makes sense with this one)
- Force MCV's redeployablility by setting the third parameter.
In `mycampaign.map`:
```ini
[Actions]
...
ID=ActionCount,[Action1],510,0,0,[MCVRedeploy],0,0,0,A,[ActionX]
...
```
In fadata.ini
```ini
[ActionsRA2]
510=Toggle MCV Redeployablility (Phobos),0,0,15,0,0,0,0,0,0, Set MCVRedeploy to the given value. 1 for yes 0 for no,0,1,510
```
> Misc `UndeploysInto` fixes and extensions

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Unit/Hooks.Jumpjet.cpp
As required from some MO players, the vanilla behavior is completely undesirable. Hence hardcode fix
> Prevent crashing jumpjet units from firing

- CREDITS.md
- Phobos.vcxproj
- docs/Fixed-or-Improved-Logics.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/Ext/Techno/Body.cpp
- src/Ext/Techno/Body.h
- src/Ext/Techno/Hooks.Disguise.cpp
- src/Ext/Techno/Hooks.cpp
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- src/Ext/TechnoType/Hooks.cpp
- `DisguiseBlinkingVisibility` can be used to customize which players can see disguises blinking on units.
- `UseDisguiseMovementSpeed`, if set, makes disguised unit adjust its movement speed to match that of the disguise, if applicable. Note that this applies even when the disguise is revealed, as long as it has not been removed.
```ini
[General]
DisguiseBlinkingVisibility=owner  ; list of Affected House Enumeration (none|owner/self|allies/ally|team|enemies/enemy|all)
[SOMETECHNO]                      ; TechnoType
UseDisguiseMovementSpeed=false    ; boolean
```
Additionally, there are following changes / fixes to the logic:
- Fixed disguised infantry not using custom palette for drawing the disguise when needed.
- Disguised infantry now show appropriate insignia when …
> Disguise logic improvements & reimplemented insignia drawing

- src/Misc/Hooks.BugFixes.cpp
Disables the seemingly unnecessary first parsing pass for AnimType/BuildingTypeClass on game initialization. Gets rid of certain parsing errors and speeds up starting the game a little bit. This is a PR instead of pushed straight to develop despite being a seemingly minor change to allow testing it separately to see if there are any unforeseen consequences.
> Disable AnimType/BuildingTypeClass first INI parsing pass

- CREDITS.md
- Phobos.vcxproj
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/House/Body.cpp
- src/Ext/House/Body.h
- src/Ext/House/Hooks.AINavalProduction.cpp
By default, while game has separate FactoryClass instances and queues for regular and naval vehicles, game still keeps track of which VehicleType to build and which one was last built using only one reference each in HouseClass. This PR decouples this for ground and naval vehicles, allowing AI to produce both simultaneously.
Because Ares reimplements the HouseClass unit production update function (`0x4FEA60`) and this feature/fix is impossible to implement without touching that function, it has been reimplemented here again using [Ares 0.A version of the function](https://github.com/Ares-Developers/Ares/blob/4f1d929920aca31924c6cd4d3dfa849daa65252a/src/Ext/House/Hooks.100.cpp#L25) as a reference. However as it stands, I have no reliable way of telling if it has been altered to any …
> Separate AI naval vehicle production from regular vehicle production

- docs/Miscellanous.md
- docs/Whats-New.md
- src/Misc/Hooks.INIInheritance.cpp
- src/Phobos.cpp
Greatly improves performance of INIsection inheritance.
Introduces "-Include" and "-Inheritance" command line arguments that enable INI file inclusion and INI section inheritance respectively, which are now disabled by default.
> Improve INI inheritance performance & add a toggle

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Misc/Hooks.BugFixes.cpp
- Fixed the bug when jumpjets were snapping into facing bottom-right when starting movement (observable when the starting unit is a jumpjet and is ordered to move).
How to test: make any jumpjet unit as a starting unit. It should be facing top right when spawned in. When you order it to move, without the fix it will snap to bottom right, with the fix it will keep the initial facing.
> Jumpjet initial facing fix

- src/Ext/Unit/Hooks.Jumpjet.cpp
- src/Misc/Hooks.BugFixes.cpp
https://github.com/Phobos-developers/Phobos/issues/1084#issuecomment-1613371056
How to test:
- pre-place jumpjet units on a map and move them, they should keep their direction and not snap into any other dir;
- use jumpjets as starting units, they also should keep the initial direction
@mevitar
> [Minor] Re-fix jumpjet initial facing

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/WeaponType/Body.cpp
- src/Ext/WeaponType/Body.h
- src/Ext/WeaponType/Hook.EBolt.cpp
By default, Electric Bolt has 8 Arcs. Now it can be customized per weapon with `IsElectricBolt=yes`
Here is example of Tesla Coil using 1 arc for primary and 32 for secondary weapon.
https://github.com/Phobos-developers/Phobos/assets/30149531/7a88a52c-e26d-44e3-b812-5e698ec0e639
Created with big help from Kerbiter
> Сustomizing Electric Bolt Arcs

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Aircraft/Hooks.cpp
- src/Ext/Building/Hooks.cpp
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/Ext/Techno/Hooks.cpp
- src/Utilities/Enum.h
- src/Utilities/TemplateDef.h
- It is now possible to customize the frame delay between instances of `[General]` -> `ChronoSparkle1` animations created on objects being warped by setting `[General]` -> `ChronoSparkleDisplayDelay`.
- By default on buildings with `MaxOccupants` higher than 0, chrono sparkle animation would be shown at each of the `MuzzleFlashN` coordinates. This behaviour is now customizable, and supports `MuzzleFlashN` indices higher than 10.
- `[General]` -> `ChronoSparkleBuildingDisplayPositions` can be set to show the sparkle animation on the building (`building`), muzzle flash coordinates of current occupants (`occupants`), muzzle flash coordinates of all occupant slots (`occupantslots`) or any combination of these.
- If `occupants` or `occupantslots` is listed without `building`, a single chrono …
> Chrono sparkle display customization & improvements

- CREDITS.md
- docs/AI-Scripting-and-Mapping.md
- docs/Whats-New.md
- src/Ext/House/Body.cpp
- src/Ext/House/Body.h
- src/Ext/Script/Body.cpp
- src/Ext/Script/Body.h
This is basically bastard child of script actions `53 Gather at Enemy Base` and `56/57 Chronoshift to Enemy Building/Target Type` 
Functions for Chronoshifting team to a specific target as well as acquiring the enemy base gather cell are separate so they can potentially be reused in future for something else if needed.
----------------------------------
- Chronoshifts the members of the TeamType using first available `Type=Chronosphere` superweapon to a location within `[General]` -> `AISafeDistance` (plus the additional distance defined in parameter, can be negative) cells from enemy house's base. The superweapon must be charged up to atleast `[General]` -> `AIMinorSuperReadyPercent` percentage of its recharge time to be available for use by this action.
In `aimd.ini`:
```ini …
```
> Add AI script action 10104 Chronoshift to Enemy Base

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/BuildingType/Hooks.cpp
- src/Ext/CaptureManager/Body.cpp
- src/Ext/CaptureManager/Body.h
- src/Ext/Techno/Hooks.DeploysInto.cpp
- src/Ext/Techno/Hooks.cpp
* Suppressed all capture events for buildings considered vehicles.
* Use `MindControl.Anim` for buildings deployed from mindcontrolled vehicles
> Fix PR #139

- CREDITS.md
- Phobos.vcxproj
- docs/Miscellanous.md
- docs/Whats-New.md
- src/Misc/SyncLogging.cpp
- src/Misc/SyncLogging.h
- src/Utilities/GeneralUtils.cpp
- src/Utilities/GeneralUtils.h
This adds following things, including relevant parameters, function caller/return address and current frame to be appended to `SYNC#.txt` log files upon desynchronization occuring:
- Last 4096 calls to game's synced random number generator function (the one that is `ScenarioClass` member) 
- Last 1024 `FacingClass::Set()` calls
- Last 1024 `TechnoClass::AssignTarget()` calls (including overrides)
- Last 1024 `TechnoClass::AssignDestination()` calls (including overrides)
- Last 256 `TechnoClass::OverrideMission()` calls
- Last 512 `AnimClass` constructor calls
These numbers can be amended later if needed. This feature is also currently enabled by default in multiplayer games only (the hooks that log this information are disabled in singleplayer/skirmish), and can incur a performance …
> Additional desync logging

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Bullet/Body.h
- src/Ext/Bullet/Hooks.cpp
- src/Ext/BulletType/Body.cpp
- src/Ext/BulletType/Body.h
- `Arcing=true` projectile elevation inaccuracy can now be fixed by setting `Arcing.AllowElevationInaccuracy=false`
- `EMPulseCannon=yes` building weapons now respect `Floater` and Phobos-added `Gravity`setting.
It is not a perfect solution as the projectiles will still miss by like 1 cell with large elevation difference. Presumably this entire problem is caused by some faulty math in `0x48A8D0` or the functions it calls as changing the fourth passed param (target height - firing height) to make it so that it never goes above zero is how I achieved these results. Figuring out the root cause is beyond me, however.
> Fix arcing elevation bug for most part

- CREDITS.md
- Phobos.vcxproj
- docs/Fixed-or-Improved-Logics.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/House/Body.cpp
- src/Ext/House/Body.h
- src/Misc/Hooks.AssignHouses.cpp
This PR renames the houses spaned on position 0-7 in MP/Skirmish to <Player @ X> and allows them to own TechnoTypes on the map, allowing for pre-placed buildings/units/etc.
> MP houses are named and allowed to house TechnoTypes owned by them on the map

- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/Building/Body.cpp
- src/Ext/Building/Body.h
- src/Ext/BuildingType/Body.cpp
- src/Ext/House/Body.cpp
- src/Ext/House/Body.h
- src/Ext/House/Hooks.cpp
- src/Ext/SWType/FireSuperWeapon.cpp
- src/Ext/Techno/Body.Update.cpp
- src/Ext/Techno/Body.h
- All AutoDeath conditions are now considered for LimboDelivery objects.
- Technos(Dont)Exist.AllowLimboed now works as expected and doesn't count units still being built.
- This required adding a new tracker and bunch of bullshit, I tested most cases but I wouldn't be surprised if I missed something.
> Fix issues with AutoDeath and limbo interactions

- CREDITS.md
- Phobos.vcxproj
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/OverlayType/Body.cpp
- src/Ext/OverlayType/Body.h
- src/Ext/OverlayType/Hooks.cpp
- src/Phobos.Ext.cpp
- Wall overlays are now drawn with the custom palette defined in `Palette` in `artmd.ini` if possible. This works identically to TechnoTypes regarding filenames and how lighting / color schemes get applied to it.
> Wall overlay custom palette support

- CREDITS.md
- Phobos.vcxproj
- docs/User-Interface.md
- docs/Whats-New.md
- src/Commands/Commands.cpp
- src/Commands/ToggleDesignatorRange.cpp
- src/Commands/ToggleDesignatorRange.h
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/Ext/SWType/Body.cpp
- src/Ext/SWType/Body.h
- src/Ext/SWType/Hooks.cpp
- src/Phobos.INI.cpp
- src/Phobos.h
* It is now possible to display range of designator and inhibitor units when in super weapon targeting mode. Each instance of player owned techno types listed in `[SuperWeapon]->SW.Designators` will display a circle with radius set in `[TechnoType]->DesignatorRange` or `Sight`.
* In a similar manner, each instance of enemy owned techno types listed in `[SuperWeapon]->SW.Inhibitors` will display a circle with radius set in `[TechnoType]->InhibitorRange` or `Sight`.
* This feature can be disabled globally with `[AudioVisual]->ShowDesignatorRange=false` or per SuperWeaponType with `[SuperWeapon]->ShowDesignatorRange=false`.
* This feature can be toggled *by the player* (if enabled in the mod) with `ShowDesignatorRange` in `Ra2MD.ini` or with "Toggle Designator Range" hotkey in "Interface" …
> Show designator & inhibitor range

- CREDITS.md
- Phobos.vcxproj
- docs/AI-Scripting-and-Mapping.md
- docs/Whats-New.md
- src/Ext/Scenario/Body.cpp
- src/Ext/Scenario/Body.h
- src/Ext/Scenario/Hooks.cpp
- src/Ext/Side/Body.cpp
- src/Ext/Side/Body.h
- src/Misc/Hooks.UI.cpp
- Toggle to show briefing screen on singleplayer mission start
- Allow setting mission par times and related messages in `missionmd.ini`
- Allow setting default singleplayer map loading screen and briefing offsets 
---------------------
- It is now possible to set defaults for singleplayer map loading screen briefing pixel offsets and the loading screen images and palette that are used if there are no values defined for the map itself.
- In `missionmd.ini`:
```ini
[Defaults]
DefaultLS640BriefLocX=0  ; integer
DefaultLS640BriefLocY=0  ; integer 
DefaultLS800BriefLocX=0  ; integer
DefaultLS800BriefLocY=0  ; integer
DefaultLS640BkgdName=    ; filename - including the .shp extension.
DefaultLS800BkgdName     ; filename - including the .shp extension.
DefaultLS800BkgdPal=     ; filename - …
```
> Misc. singleplayer mission additions / improvements

- src/Ext/SWType/FireSuperWeapon.cpp
It's been reported that LimboKill causes
* Game crash when using `Academy.xxxVeterancy` from Ares
* xxxGainSelfHeal effect not being removed
* OrePurifier multiplier duplication when delivered and remaining effect after LimboKill-ed
By using the game's original limbo deletion routine prevents this
> Fix LimboKill not working properly, Fix LimboDeliver doubles OrePurifier multiplier

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- src/Ext/TechnoType/Hooks.cpp
- src/Utilities/GeneralUtils.h
Originally authored by @chaserli
- Attempt to fix the math of shadow projection (turrets being off kilter etc).
- Attempt to make multi-section shadows consider frame index.
- Fix shadow flickering with multi-section voxels using the HVA transform section swap method.
- Airborne voxel shadow scaling.
TODO:
- Regression tests with lots of voxels
---------------
Update from @chaserli 02/29:
* Considered Ares turrets/barrels, fixed wrong voxel selection especially in charging turret cases
* Added 2 new tags for the hva frame of each you want to render the shadow.
* If you only want to render the ShadowIndex as usual but the VXL used the socalled hva section swap method, then naturally the hva matrix for the first frame is not null, so ShadowIndex.Frame is default to 0
* If you set …
> Voxel turret & multi-section shadow reimplementation

- src/Ext/RadSite/Hooks.cpp
- src/Ext/Side/Body.cpp
- src/Ext/WarheadType/Detonate.cpp
- src/Utilities/Container.h
> [Minor] Attempt to weaken radside desync

- CREDITS.md
- Phobos.vcxproj
- docs/Fixed-or-Improved-Logics.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- src/Ext/WarheadType/Body.cpp
- src/Ext/WarheadType/Body.h
- src/Ext/WarheadType/Detonate.cpp
- src/Misc/Hooks.BugFixes.cpp
- src/Misc/Hooks.Crates.cpp
- src/Utilities/TemplateDef.h
- Warheads can now spawn powerup crates of specified type(s) on their impact cells (if free, or nearby cells if occupied something other than a crate) akin to map trigger action 108 ('Create Crate').
- `SpawnsCrateN` where N is a number starting from 0, parsed until no key is found can be used to define the type of crate spawned.
- `SpawnsCrateN.Weight` is a number that determines relative weighting of spawning corresponding crate type vs. other listed ones (0 is no chance, higher means higher probability) defaulting to 1 if not defined.
- `SpawnsCrate.Type/Weight` is an alias for `SpawnsCrate0.Type/Weight` if latter is not set.
```ini
[SOMEWARHEAD]            ; Warhead
SpawnsCrate(N).Type=     ; Powerup crate type enum …
```
> Spawn crates /w Warheads & minor crate improvements

- docs/Whats-New.md
- src/Utilities/Helpers.Alex.h
Fixes effect + `CellSpread`to interaction with buildings correctly e.g hitting any cell on foundation counts as a hit instead of having to hit the top-leftmost cell (cell 0).
Also reimplemented air unit checks using `AircraftTrackerClass`.
> Improve Phobos warhead effect CellSpread behaviour

- src/Ext/House/Hooks.cpp
- src/Ext/Techno/Hooks.cpp
`HouseClass::IsHumanPlayer` can't cover the case when player is controlling multiple houses in campaign. Should use `HouseClass::IsControlledByHuman()` in these cases.
> [Minor] Change a human player condition

- CREDITS.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/Aircraft/Hooks.cpp
- src/Ext/Techno/Body.cpp
- src/Ext/Techno/Body.h
- src/Ext/WeaponType/Body.cpp
- src/Ext/WeaponType/Body.h
Now works with any projectile (no longer requires ROT <=1)
> Strafing.Shots > 5

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Aircraft/Hooks.cpp
- src/Ext/Techno/Body.cpp
- src/Ext/WeaponType/Body.cpp
- src/Ext/WeaponType/Body.h
- In yuri's revenge, if aircraft has passengers, aircraft force kick out it's passengers when firing but not fire weapons.
- Now you can decide aircraft kick out it's passengers or not when firing.
```ini
[SOMEWEAPON]
KickOutPassenger=true  ; boolean 
```
> Customizing whether passengers are kicked out when an aircraft fires

- docs/User-Interface.md
- docs/Whats-New.md
- src/Ext/Techno/Body.Visuals.cpp
- src/New/Type/DigitalDisplayTypeClass.cpp
- src/New/Type/DigitalDisplayTypeClass.h
- `Offset` and `Offset.ShieldDelta` Y-axis offset behaved inconsistently compared to everything else in the game, with negative values shifting down and positive up. It now works the other way around like `PixelSelectionBracketDelta`, `YDrawOffset` etc. do.
- Added `ValueScaleDivisor` (taking suggestions for name) that can be used to adjust the scale of displayed values. This is given as an integer to prevent rounding issues with floating point values and is used to divide the values.
> Couple of minor digital display improvements

- CREDITS.md
- docs/AI-Scripting-and-Mapping.md
- docs/Whats-New.md
- src/Ext/Script/Body.cpp
- src/Ext/Script/Body.h
- src/Ext/Team/Body.cpp
- src/Ext/Team/Body.h
It can allow the team to go back to previous script and continue the lines after action 94.
And it can be used in multiple layers, like the example:
example:
in aimd.ini:
```
[s1]
Name=test1
0=54,0
1=94,18
2=0,1
[s2]
Name=test2
0=42,0
1=5,5
2=94,19
3=134,0
[s3]
Name=test3
0=42,2
1=5,5
2=94,20
3=134,0
[s4]
Name=test4
0=42,4
1=5,5
2=134,0
```
in rulesmd.ini:
```
[AIScriptsList]
18=s2
19=s3
20=s4
```
https://user-images.githubusercontent.com/55939089/177151602-0a5e2310-8c54-47b0-bb8f-70d57a6c302d.mp4
> New action 134 Jump Back To Previous Script after action 94

- CREDITS.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/BuildingType/Hooks.Upgrade.cpp
- src/Ext/House/Body.cpp
- src/Ext/House/Body.h
- src/Ext/House/Hooks.cpp
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
Different technos can now share build limit within a group. Originally implemented by ststl. I've gotten the permission to transplant it to mainline Phobos and make further enhancement on it.
- `BuildLimitGroup.Types` determines the technos that'll be used for build limit conditions of the selected techno.
- `BuildLimitGroup.Nums` determines the amount of technos that would reach the build limit. If using a single integer, it'll use the sum of all technos in the group to calculate build limit. If using a list of integers with the same size of `BuildLimitGroup.Types`, it'll calculate build limit per techno.
- `BuildLimitGroup.ContentIfAnyMatch` determines the rule of calculating build limit per techno. If set to true, build limit will be content if the amount of any techno in the group …
> Build limit group

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Misc/Hooks.BugFixes.cpp
An attempt to fix an issue where the ATC->CurrentVector does not contain every air Techno in given range that increases in frequency as the range goes up.
Real talk: I have absolutely no clue how the original function works besides doing vector looping and manipulation, as far as I can tell it never even explicitly clears CurrentVector but somehow it only contains applicable items afterwards anyway. It is possible this one does not achieve everything the original does functionality and/or performance-wise but it does work and produces results with greater accuracy than the original for large ranges.
> Possible fix to AircraftTrackerClass range issue

- src/Ext/House/Body.cpp
- src/Ext/House/Body.h
- src/Ext/House/Hooks.cpp
- src/Ext/SWType/FireSuperWeapon.cpp
- src/Ext/Scenario/Body.cpp
- src/Ext/Scenario/Body.h
- src/Ext/Techno/Body.Update.cpp
- src/Ext/Techno/Body.cpp
- src/Ext/Techno/Hooks.Transport.cpp
Techno with ReloadInTransport=yes suffered from a crash when the transporter's owner is changed (i.e. being mind controlled). This is because it'll move the techno from the original owner's OwnedTransportReloader list to the new owner's, which is actually wrong when the transporter doesn't have Passengers.SyncOwner=yes. Attempted to fix this issue and unified the conditions of ReloadInTransport
> [Minor][Needs testing] Attempt to fix the ReloadInTransport crash

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/Misc/Hooks.BugFixes.cpp
- Vanilla game applies some weird unnecessary math which resulted in light being applied incorrectly on tilted voxels and the light source being "nudged" up by a bit. It is now possible to fix that.
```ini
[AudioVisual]
UseFixedVoxelLighting=false ; boolean, whether to fix the lighting
```
> Voxel light source position/tilting fix

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Building/Hooks.cpp
- src/Ext/BuildingType/Body.cpp
- src/Ext/BuildingType/Body.h
- src/Ext/House/Body.cpp
- src/Ext/House/Body.h
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- src/Ext/TechnoType/Hooks.cpp
- It is now possible to customize which TechnoTypes benefit from bonuses of a `FactoryPlant=true` building by listing them on `FactoryPlant.AllowTypes` and/or `FactoryPlant.DisallowTypes`.
- `FactoryPlant.Multiplier` (Ares feature) is still applied on the bonuses if they are in effect.
```ini
[SOMEBUILDING]               ; BuildingType
FactoryPlant.AllowTypes=     ; List of TechnoTypes
FactoryPlant.DisallowTypes=  ; List of TechnoTypes
```
> Add allowed / disallowed type lists for FactoryPlant

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/OverlayType/Body.cpp
- src/Ext/OverlayType/Body.h
- src/Ext/OverlayType/Hooks.cpp
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/Ext/TerrainType/Body.cpp
- src/Ext/TerrainType/Body.h
- src/Ext/TerrainType/Hooks.cpp
- src/Utilities/GeneralUtils.cpp
- src/Utilities/GeneralUtils.h
- Length of the animation can now be customized by setting `AnimationLength` as well, defaulting to half (or quarter if damaged frames are enabled) the number of frames in TerrainType's image.
```ini
[SOMETERRAINTYPE]  ; TerrainType
AnimationLength=   ; integer, number of frames
```
- By default game shows damage frame only for TerrainTypes alive at only 1 point of health left. Because none of the original game TerrainType assets were made with this in mind, the logic is now locked behind a new key `HasDamagedFrames`.
- Instead of showing at 1 point of HP left, TerrainTypes switch to damaged frames once their health reaches `[AudioVisual]` -> `ConditionYellow.Terrain` percentage of their maximum health. Defaults to `ConditionYellow` if not set.
- In addition, …
> New & restored TerrainType features

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Building/Hooks.cpp
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- You can also exclude specific TechnoTypes from being built in parallel by AI by setting `ForbidParallelAIQueues` to true on a TechnoType.
```ini
[SOMETECHNO]                  ; TechnoType
ForbidParallelAIQueues=false  ; boolean
```
In addition, `ForbidParallelAIQueues` seemed to have some problems working, particularly with VehicleTypes. Resetting the current factory after unit is kicked out *seemed* to fix this but I am unsure if there are any unforeseen consequences. I have not noticed any so far myself.
> Allow forbidding parallel AI queues for specific TechnoTypes

- CREDITS.md
- docs/Whats-New.md
- src/Ext/SWType/FireSuperWeapon.cpp
Fix a mistake of `LimboKill` that it did not update the iterators correctly that cause it unable to correctly remove all buildings with the same ID.
> [Minor] Fix LimboKill function

- CREDITS.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/SWType/Body.cpp
- src/Ext/SWType/Body.h
- src/Ext/SWType/FireSuperWeapon.cpp
- src/Ext/SWType/Hooks.cpp
- Now you can specific sw will insert to which tab of sidebar.
```ini
[SOMESW]                    ; Super Weapon
TabIndex=1                  ; integer
```
> Assign Super Weapon cameo to any sidebar tab

- CREDITS.md
- docs/AI-Scripting-and-Mapping.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/House/Body.cpp
- src/Ext/House/Body.h
- src/Ext/House/Hooks.cpp
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/Ext/Scenario/Body.cpp
- src/Ext/Techno/Hooks.Misc.cpp
- In vanilla, there is a hardcoded behavior that when an skirmish AI player has no factory and has not taken damage for a while, it will sell its buildings and set its units to hunt. This can be customized now.
- `[General]->AISellAllOnLastLegs` and `[General]->AIAllInOnLastLegs` control whether the AI will act selling and hunting respectively.
- `[General]->AISellAllDelay` defines a timer, it will only work if `[General]->AISellAllOnLastLegs` is set to `true`. When the first time the AI reaches the trigger condition of vanilla behavior, the timer starts and prevents the selling behavior from happening until the timer is expired.
- You can use these flags to make the AIs "all in" before they are defeated.
- Another hardcoded behavior is that, when the AI deploys a MCV, it will regroup all …
> Two skirmish AI behavior dehardcoded and a minor improvement

- CREDITS.md
- Phobos.vcxproj
- docs/Fixed-or-Improved-Logics.md
- docs/User-Interface.md
- docs/Whats-New.md
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/Ext/WarheadType/Body.cpp
- src/Ext/WarheadType/Body.h
- src/Misc/Hooks.LightEffects.cpp
- src/Phobos.INI.cpp
- src/Phobos.h
- You can now set minimum detail level at which combat light effects are shown by setting `[AudioVisual]` -> `CombatLightDetailLevel` or `CombatLightDetailLevel` on Warhead, latter defaults to former.
- You can now set a percentage chance a combat light effect is shown on Warhead impact by setting `CombatLightChance`.
```ini
[AudioVisual]
CombatLightDetailLevel=0                     ; integer
[SOMEWARHEAD]                                ; WarheadType
CombatLightDetailLevel=                      ; integer
CombatLightChance=1.0                        ; floating point value, percents or absolute (0.0-1.0)
```
- It is possible to toggle certain light flash effects off. These light flash effects include:
- Combat light effects (`Bright=true`) and everything that uses same …
> Light effect customizations

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Building/Hooks.cpp
- src/Ext/BuildingType/Body.cpp
- src/Ext/BuildingType/Body.h
- src/Misc/Hooks.BugFixes.cpp
- It is now possible to customize the repairing of units by `UnitRepair=true` and `UnitReload=true` buildings.
- `Units.RepairRate` customizes the rate at which the units are repaired. This defaults to `[General]`->`ReloadRate` if `UnitReload=true` and if overridden per AircraftType (Ares feature) can tick at different time for each docked aircraft. Setting this overrides that behaviour. For `UnitRepair=true` buildings this defaults to `[General]`->`URepairRate`.
- On `UnitReload=true` building setting this to negative value will fully disable the repair functionality.
- `Units.RepairStep` how much `Strength` is restored per repair tick. Defaults to `[General]`->`RepairStep`.
- `Units.RepairPercent` is a multiplier to cost of repairing (cost / (maximum health / repair step)). Defaults to …
> Allow customizing dock unit repair

- CREDITS.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/BuildingType/Body.cpp
- src/Ext/BuildingType/Body.h
- src/Ext/BuildingType/Hooks.cpp
- There are now additional customizations available for building placement next to other buildings.
- `Adjacent.Allowed` lists BuildingTypes this BuildingType can be placed off (within distance defined by `Adjacent`). If empty, any BuildingType not listed in `Adjacent.Disallowed` is okay.
- `Adjacent.Disallowed` lists BuildingTypes this BuildingType cannot be placed next to. If empty, any BuildingTypes are okay as long as `Adjacent.Allowed` is empty or they are listed on it.
- If `NoBuildAreaOnBuildup` is set to true, no building can be built next to this building regardless of any other settings if it is currently displaying its buildup animation.
```ini
[SOMEBUILDING]              ; BuildingType
Adjacent.Allowed=           ; list of BuildingTypes
Adjacent.Disallowed= …
```
> Build area customizations

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Anim/Body.cpp
- src/Ext/Anim/Body.h
- src/Ext/Anim/Hooks.cpp
- src/Ext/AnimType/Body.cpp
- src/Ext/AnimType/Body.h
- src/Utilities/Enum.h
- src/Utilities/TemplateDef.h
- Tiberian Sun allowed `Scorch=true` and `Flamer=true` animations to spawn fire animations from `[AudioVisual]` -> `SmallFire` & `LargeFire`. This behaviour has been reimplemented and is fully customizable.
- `ConstrainFireAnimsToCellSpots` controls whether or not spawned animations are locked to cell spots (e.g the subcell positions infantry are also constrained to).
- `FireAnimDisallowedLandTypes` controls which landtypes the fire animations are not allowed to spawn on. Defaults to `water,rock,beach,ice` for `Scorch=true`, `none` otherwise.
- `AttachFireAnimsToParent` controls if the spawned animations are attached to the owner of the parent animation if it is also attached. Defaults to true for `Scorch=true`, otherwise false.
- `SmallFireCount` determines number of small fire …
> Scorch / Flamer fire animation spawning customization

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/Building/Body.cpp
- src/Ext/Building/Body.h
- src/Ext/Building/Hooks.cpp
- src/Ext/House/Body.cpp
- src/Ext/House/Body.h
- src/Ext/SWType/Body.cpp
- src/Ext/SWType/Body.h
- src/Ext/SWType/FireSuperWeapon.cpp
- src/Ext/SWType/Hooks.cpp
- src/Ext/SWType/SWHelpers.cpp
- It is possible to customize which weapon a building with `EMPulseCannon=true` fires when an associated `Type=EMPulse` superweapon (**only** if `EMPulse.TargetSelf=false` or omitted) is fired by setting `EMPulse.WeaponIndex`.
- Note that if you fire another `Type=EMPulse` superweapon with different weapon index that the same building is capable of launching before the first weapon was fired, the latter superweapon's settings will take precedence.
- Additionally, due to technical limitations the targeting constraints will always default to primary weapon's `Range/MinimumRange` unless `SW.RangeMinimum/SW.RangeMaximum` are explicitly set.
- Is is now also possible to have all other `Type=EMPulse` superweapons that can be fired by same buildings as current one be put on hold until first of …
> EMPulse improvements

- docs/Whats-New.md
- src/Ext/SWType/FireSuperWeapon.cpp
- src/Ext/WarheadType/Detonate.cpp
Previously when `LaunchSW.IgnoreInhibitors` or `SW.Next.IgnoreInhibitors` set to true, it'll override the settings of corresponding `IgnoreDesignators` and make their conditions always satisfied, which is fixed now.
> [Minor] Fix IgnoreInhibitors overriding IgnoreDesignators

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/New-or-Enhanced-Logics.md
- docs/User-Interface.md
- docs/Whats-New.md
- src/Ext/House/Body.cpp
- src/Ext/House/Body.h
- src/Ext/SWType/Body.cpp
- src/Ext/SWType/Body.h
- src/Ext/SWType/FireSuperWeapon.cpp
- src/Misc/PhobosToolTip.cpp
- src/Misc/PhobosToolTip.h
- src/Phobos.INI.cpp
- src/Phobos.h
uimd.ini`[ToolTips]->SWShotsFormat` csf entry default to `Shots : %d`
> Append Ares' SW.Shots usage to sw tooltip

- src/Ext/TEvent/Body.cpp
Trigger event 601 & 602 don't work properly in single player maps, while 604 & 605 do. The only distinction between them is what I've changed. You can test the result with this map:
[all01umd.zip](https://github.com/user-attachments/files/17784794/all01umd.zip)
By the way, phobos's new events and actions use FindByIndex/Array->GetItem instead of FindByCountryIndex, which leads to  inconsistency with the vanilla events and actions, for they use country index instead of house index. In single player map with whole new houses (like official RA2 campaign, they use BadGuy1, GoodGuy1 etc.), it begins with 14 by country index, but 0 by house index. This may make map editing and FA2 adaptation more complicated, so I want to know your opinions.
If you want to restore the vanilla habit, just modify …
> [Minor]fixed bug that event 601 & 602 don't work properly in single player maps

- src/Utilities/Helpers.Alex.h
Fix the issue of attaching effects (EMP, IC, AE...) to technos that are out of cell spread range.
> [Minor] Fix build-45’s issue of excessive cell spread effect range

- docs/Fixed-or-Improved-Logics.md
&grave;Flamer? -> `Flamer`
A very minor error that affects users' reading and comprehension.
It made me wait for two months without seeing anyone fix it.
So, I decided to take care of it myself.
That's all.
> [Minor] Fix an error in a Markdown formatted character in the document.

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Misc/Hooks.BugFixes.cpp
- src/Utilities/AresAddressInit.cpp
- src/Utilities/AresFunctions.h
Bug Description:
This is a fix to the Ares bug: Academy feature doesn't apply to the initial payload of vehicles built off a War Factory. Curiously, Academy applies to the initial payloads of vehicles under any other circumstances, even when built off a Naval Shipyard.
Cause:
It is "Unsorted::IKnowWhatImDoing" prevented the "HouseExt::ApplyAcademy" from taking effect.
Fix:
The fix is simple, when Ares is supposed to have initialized the initial payload, and Academy is prevented from taking any effect, temporarily turn off "Unsorted::IKnowWhatImDoing", invoke "HouseExt::ApplyAcademy", then turn on "Unsorted::IKnowWhatImDoing" again.
> [Minor] [Ares Fix] Ares academy fix

- CREDITS.md
If you don't know it yet: Phobos has an active Chinese tester group which helps with new function testing and crash/desync hunting. Now that 0.4 is on the pipeline, I'd like to credit these players for assisting Phobos development
> [Minor] Phobos Tester Credits

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Team/Hooks.cpp
[Ares](https://github.com/Ares-Developers/Ares/commit/1b8b66f4d3892509f565eabce7efd59a9f3dbed4) marked its initialpayload already created for units spawned by trigger actions because of the mutex.
> Fix Ares' InitialPayload for teams spawned by trigger actions

- src/Misc/Hooks.BugFixes.cpp
Fix the problem caused by the incorrect return address of the hook in b37 repair.
Skipping repeated check. And avoiding RE caused by uninitialized different data in EBX of different players.
> [Minor] Fix a RE caused by `DeployToFire`

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Aircraft/Hooks.cpp
1. Fix aircrafts planning waypoint problem - At the end of each task, all units with planning waypoints will generate an mega event to the next planning waypoint and respond after 1 frame. This is really no problem for most units, but for aircrafts, they will always return to the airport after each task. So they will try to return to the airport in the frame before it respond to event. There will be looked like a "shaking", if the `Speed` and `ROT` of the aircraft are fast. To solve this problem, I check the waypoints of aircrafts and let them wait before returning.
2. Fix a vanilla issue - Now aircrafts can fly towards the water surface normally.
> More aircraft actions enhancement for #1366

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Misc/Hooks.BugFixes.cpp
- Now the team members use the 2D distance instead of the 3D distance to judge whether to reach the mission destination, so as to prevent the problem that the mission is stuck and cannot continue in some cases (such as when the jumpjet stops on the building).
> Use 2D distance to check whether team members have arrived destination

- src/Ext/Bullet/Hooks.cpp
- src/Ext/Bullet/Trajectories/PhobosTrajectory.cpp
- src/Ext/Bullet/Trajectories/SampleTrajectory.cpp
- src/Ext/Bullet/Trajectories/SampleTrajectory.h
Update the old template of Trajectory=Sample, add some comments. And make some uniform changes for Trajectories: 1. Avoid inertia effect on trajectories fired by aircrafts; 2. Draw laser trails with the actual moving direction of the projectile.
> [Minor] Update Trajectory Template and Uniform Trajectory Modifications

- docs/New-or-Enhanced-Logics.md
`CreareUnit.SpawnHeight` -> `CreateUnit.SpawnHeight`
Checked the source code to confirm
> Handling Key Name Errors

- src/Ext/Bullet/Trajectories/StraightTrajectory.cpp
- Fix when `Trajectory=Straight` bullet with `Trajectory.Straight.ProximityMedial=true` is attacking a large building, the warhead may snap to the center of the building. #1499 
- Fix when `Trajectory=Straight` bullet with a large `Trajectory.Straight.ProximityRadius` and a low `Trajectory.Speed`, the final speed may suddenly increase and rush out of range.
> [Minor] Fix two issues of enhanced straight trajectory

- src/Ext/Bullet/Hooks.DetonateLogics.cpp
`ExtraWarheads.DetonationChances` and `ExtraWarheads.FullDetonation`.
> [Minor] Fix `ExtraWarheads` always read the last setting

- src/Ext/BuildingType/Body.cpp
- src/Ext/BuildingType/Body.h
- src/Ext/House/Body.cpp
- src/Ext/House/Hooks.cpp
Vanilla and Ares all only hardcoded to find factory with `BuildCat::DontCare`...
> [Minor] Fix Defenses Production Queue's Issue

- src/Ext/Building/Hooks.cpp
- src/Ext/House/Hooks.cpp
- src/Ext/Sidebar/Body.cpp
- src/Ext/Sidebar/Body.h
- src/Misc/Hooks.Ares.cpp
Fix an issue: When the defensive buildings in the queue lose their prerequisites, they will not be cancelled but will remain stuck forever. (This issue does not occur when using #1477 )
The problem still comes from hardcoded `BuildCat::DontCare`.
> [Minor] Fix building production queue issue

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Techno/Body.cpp
- src/Ext/Techno/Body.h
- src/Ext/Techno/Hooks.cpp
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- It is now possible for vehicles to retain their target when issued movement command by setting `KeepTargetOnMove` to true.
- Note that no check is done whether or not the vehicle or the weapon can actually fire while moving, this is on modder's discretion.
- The target is automatically reset if the vehicle moves beyond the weapon's range from the target.
- `KeepTargetOnMove.ExtraDistance` can be used to modify the distance considered 'out of range' from target (it is added to weapon range), negative values work to reduce the distance.
```ini
[SOMEVEHICLE]                     ; VehicleType
KeepTargetOnMove=false            ; boolean
KeepTargetOnMove.ExtraDistance=0  ; floating point value, distance in cells
```
> Allow vehicles to retain target on move command

- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/Ext/Techno/Hooks.Firing.cpp
- src/Ext/Techno/WeaponHelpers.cpp
Phobos previously added a rule to select weapons based on `[Warhead] ► Wall= (bool)`
but `[TechnoType] ► NoSecondaryWeaponFallback= (bool)` cannot disable this rule
this causing the Soviet Siege Chopper to use the `160mm` weapon to attack walls even when not deployed.
> NoSecondaryWeaponFallback can now cancel the weapon selection for walls.

- docs/New-or-Enhanced-Logics.md
- src/Ext/Techno/Body.Update.cpp
- src/Ext/Techno/Body.cpp
- src/Ext/Techno/Body.h
- src/Ext/Techno/Hooks.Misc.cpp
- src/Ext/Unit/Hooks.Jumpjet.cpp
- src/New/Type/Affiliated/PassengerDeletionTypeClass.cpp
- src/New/Type/Affiliated/PassengerDeletionTypeClass.h
For consistency: if `IsUnderEMP` is checked, then the techno's `Deactivated` should be checked in the same time. Added the remaining few cases where it's not being checked.
A logic that might be influence by this is `PassengerDeletion`, and idk why it even needs to check if the transport is EMP'd in the first time. Hence, I've added a tag to customize if passenger deletion should still be processed in such case.
```ini
[SOMETECHNO]                                    ; TechnoType
PassengerDeletion.UnderEMP=false                ; boolean
```
> [Minor] Deactivated check & allow passenger deletion under EMP

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Misc/Hooks.BugFixes.cpp
- Fix an issue where a unit will leave an impassable invisible barrier in its original position when it is teleported by ChronoSphere onto an uncrushable unit and self destruct.
Thx to @NetsuNegi .
> [Vanilla Fix] Fix impassable invisible barrier created by chronosphere on uncrushable unit

- src/Ext/Building/Hooks.cpp
> [Minor] Disallow other actions for building in planning mode

- src/Ext/TechnoType/Hooks.MatrixOp.cpp
Now ground units being lifted will not turn to attacker weirdly.
> [Minor] Ground units being lifted will not turn to attacker

- src/Ext/Anim/Hooks.AnimCreateUnit.cpp
- src/Ext/Anim/Hooks.cpp
- src/Ext/House/Body.cpp
- src/Ext/RadSite/Body.cpp
- src/Ext/Techno/Body.Update.cpp
- src/Ext/Techno/Body.cpp
- src/Ext/Techno/Hooks.Firing.cpp
- src/Ext/TechnoType/Body.cpp
- src/Ext/TerrainType/Hooks.cpp
- src/Misc/Hooks.Crates.cpp
- NearByLocation may return CellStruct::Empty, it should be checked.
- TryGetCellAt and GetCellAt are being misused, I inferred the intended usage based on the code, but I am not sure if this is the original authors' idea.
> [Minor] Add validity check for NearByLocation and fix incorrect usage of TryGetCellAt and GetCellAt

- docs/New-or-Enhanced-Logics.md
- src/Ext/Bullet/Body.cpp
- src/New/Type/Affiliated/InterceptorTypeClass.cpp
- src/New/Type/Affiliated/InterceptorTypeClass.h
Interceptor is supposed to be affected by the firer's firepower multipliers, but the previous implementation is missing new attach effect's multiplier. While I once wanted to add it directly, I'm afraid that not everyone want to use AE to affect interceptor's damage. Hence I've added an `Interceptor.ApplyFirepowerMult` tag that'll determine whether or not the intercepting weapon's damage should multiply the TechnoType's firepower multipliers.
> [Minor] Interceptor.ApplyFirepowerMult

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- docs/locale/zh_CN/LC_MESSAGES/CREDITS.po
- docs/locale/zh_CN/LC_MESSAGES/Fixed-or-Improved-Logics.po
- src/Misc/Hooks.BugFixes.cpp
`FreeUnit` uses the unit's own `SpeedType` to find the spawn location.
The bug where naval ships as StartUnit might spawn on land has been fixed.
When a building undeploy, it will normally use the target VehicleType's pathfinding method to decide whether it can move to the target cell.
> Fix Pathfinding Bugs by Decoupling SpeedType from Hardcoded Values

- src/Ext/BuildingType/Body.cpp
Fix the bug that `IsAnimDelayedBurst` and `ZShapePointMove.OnBuildup` can only be used when own section name is the same as image section name.
> [Minor] Fix art section reading bug

- src/Ext/Techno/Body.cpp
- src/Misc/Hooks.Ares.cpp
AFAIK, `Detach()` is only called inside `TemporalClass`. All external calls use `LetGo` (for most cases) or `JustLetGo` (when used for DestroyAll).
> [Minor] Fix incorrect interaction between techno convertion and chrono weapon

- src/Misc/Hooks.BugFixes.cpp
Fix incompatiblity with https://github.com/CnCNet/yrpp-spawner/pull/27
> Fix incorrect implementation of tunnel loco speed

- docs/New-or-Enhanced-Logics.md
- src/Ext/Techno/Hooks.cpp
- Set this to `true` on a building with `UndeploysInto` set could prevent it from undeploying when setting the rally point.
> [Minor] `NoManualMove` for buildings

- src/Ext/Building/Hooks.cpp
- src/Ext/Techno/Body.Update.cpp
- src/Ext/Techno/Body.cpp
- src/Ext/Techno/Body.h
- src/Ext/Techno/Hooks.cpp
- src/Ext/TechnoType/Hooks.Teleport.cpp
Splits functionality away from `TechnoClass_AI` / `TechnoExt::OnEarlyUpdate()` that does not need to be processed for all types of technos.
- Splits logic concerning `FootClass` only from `TechnoExt::UpdateTypeData()` to `TechnoExt::UpdateTypeData_Foot()` called from `FootClass_AI`. While `OpenTopped` is read for all technos, it does not work correctly for buildings so it was also moved.
- Moves tunnel enter / exit processing and relevant hooks entirely to appropriate update functions instead of general ones.
- `TechnoExt::DepletedAmmoActions()` is now called from `UnitClass_AI` (not a new hook - was repurposed/generalized from `KeepTargetOnMove` feature which was split into its own function too).
- `TechnoExt::UpdateGattlingRateDownReset()` is now called from `UnitClass_AI` and …
> Optimize per-frame update logic

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Bullet/Body.cpp
- src/Ext/Techno/Body.cpp
- src/Ext/Techno/Body.h
- src/Ext/WeaponType/Body.cpp
- src/Ext/WeaponType/Body.h
- src/Ext/WeaponType/Hook.EBolt.cpp
- src/Misc/Hooks.BugFixes.cpp
- src/Phobos.Ext.cpp
- Reverts the previous, partial or non-functional fixes for crash at `0x4C2C19`.
- Replaces the code for handling tracking of electric bolts and their owner technos to support multiple electric bolt instances per techno (vanilla tracks this with single pointer in UnitClass only). This tracking code also correctly works for units in limbo which should prevent the aforementioned crash from occuring at all.
- This tracking is used to determine whether or not the electric bolt updates its source coordinate based on FLH on every frame, allowing it to follow techno's rotation, movement etc. By default this is only enabled for vehicles just as before but can be overridden per weapon by explicitly setting value for `Bolt.FollowFLH`. It now correctly takes burst into accord thanks to changes …
> Fixes & improvements to electric bolt handling

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Misc/Hooks.BugFixes.cpp
WW uses `SetDesired` on `BarrelFacing`, which causes the barrel image cache to be incorrectly initialized.
> [Vanilla Fix] Fixed an issue where `FireAngle` would not work properly under certain circumstances.

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Misc/Hooks.BugFixes.cpp
- Technos are no longer unable to stop when it is above the elevated bridge.
- Technos are still not allowed to stop moving under the elevated bridge, but can stop other missions.
> [Vanilla Fix] More `Stop` command fix

- docs/Fixed-or-Improved-Logics.md
- src/Ext/Aircraft/Hooks.cpp
Aircraft not have to fly directly above the airport before starting to descend. Also use `ExtendedAircraftMissions` to control.
> [Minor] Aircraft early descend its flight level

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Building/Hooks.Grinding.cpp
- src/Ext/Techno/Hooks.Transport.cpp
- src/Misc/Hooks.Ares.cpp
- src/Misc/Hooks.BugFixes.cpp
- Fixed an issue that `MovementZone=AmphibiousDestroyer` and `MovementZone=AmphibiousCrusher` technos being unable to enter on water structures.
> [Vanilla & Ares Fix] Fixed an issue that some amphibious technos being unable to enter on water structures

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Bullet/Hooks.Obstacles.cpp
- src/Misc/Hooks.BugFixes.cpp
- Fixed an issue that aircraft carriers can not find suitable locations for attacks when under elevated bridges on their own.
- Fixed an issue that in air aircraft carriers being unable to attack when it is near by elevated bridges.
- Fixed an issue that aircraft carriers cannot retract its spawned aircraft when on the bridge.
> [Vanilla Fix] Fix interaction issue between aircraft carriers and elevated bridges

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Misc/Hooks.BugFixes.cpp
Fixed an issue where the shadow of jumpjet remained on the ground when it was above the elevated bridge (layer problem not fixed).
> [Vanilla Fix] Fix jumpjet shadow issue on elevated bridge

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/Ext/Techno/Hooks.cpp
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- In vanilla, units using drive/ship loco will has hardcoded speed multiplier when damaged. Now you can customize it.
- The max valuebale value is 1.0, you cannot make unit get faster on yellow condition by it.
```ini
[General]
DamagedSpeed=0.75        ; double
[SOMEUNIT]
DamagedSpeed=            ; double
```
> [Dehardcode]Customize damaged speed

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Misc/Hooks.BugFixes.cpp
- Fix the bug that `EnterBioReactorSound` and `LeaveBioReactorSound` on technotype does not used.
- Fix the bug that harvester dont stop unloading and cannot unload cargos anymore when lifting by `IsLocomotor=yes` warhead.
> [Vanilla Fix] 2 bugfixes

- CREDITS.md
- Phobos.vcxproj
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- src/Ext/Unit/Hooks.Harvester.cpp
- Now you can limit how much ore the harvester can dump out per time, like it in Tiberium Sun.
- 现在你可以限制矿车每次能倾倒出多少矿石，就像《泰伯利亚之日》中的那样。
- Less than or equal to 0 means no limit, it will always dump out all at one time.
- 小于等于0意味着没有限制，它总是一次性倒光全部矿石。
```ini
[General]
HarvesterDumpAmount=0.0               ; float point value
[SOMEVEHICLE]
HarvesterDumpAmount=                  ; float point value
```
> [Vanillia Enhancement] Customize harvester dump amount

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Misc/Hooks.BugFixes.cpp
- Fixed an issue that game crashes (EIP:7FB178) when infantry are about to enter an occupiable building that has been removed and is not real dead.
- Fixed an issue that game crashes when spawnee has been removed and is not real dead.
---
PS: such as sell action, vanish by auto death or removed by temporal weapon.
> [Vanilla Fix] Two fixes related to abnormal deaths

- CREDITS.md
- Phobos.vcxproj
- docs/AI-Scripting-and-Mapping.md
- docs/Whats-New.md
- src/Ext/House/Body.cpp
- src/Ext/House/Body.h
- src/Ext/House/Hooks.ForceEnemy.cpp
- src/Ext/TAction/Body.cpp
- src/Ext/TAction/Body.h
This is the third time it's been pushed, and I don't know why every forced merge causes PR to shut down.
Function for three trigger actions 606-608:
- 606: Edit the hate-value that triggers houses against specified house. -1 for all houses.
- 607: Clear the hate-value that triggers houses against specified house. -1 for all houses
- 608: Set a forced enemy that is not affected by hate-value. -1 will remove forced enemies, -2 will force no enemies.
----------------------
这是第三次推送它了，我不知道为什么每次强制合并都会导致PR关闭。
功能为三个触发动作 606-608：
- 606 : 编辑触发所属方对指定所属方的仇恨值。-1为全部所属方。
- 607 : 清除触发所属方对指定所属方的仇恨值。-1为全部所属方。
- 608 : 设置一个不会被仇恨值影响的强制敌人。-1删除强制敌人，-2强制没有敌人。
> Map Action 606-608

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/House/Hooks.ForceEnemy.cpp
- src/Ext/TAction/Body.cpp
when a certain house was defeated, the Ares.dll crashed due to writing incorrect parameters. now I'm trying to solve this problem.
---------
由于写入了错误的参数导致某个所属方战败时Ares.dll崩溃了，我正在尝试解决这个问题。
> [minor] Fix the AddAnger conflict with Ares.dll

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Aircraft/Hooks.cpp
- src/Ext/Techno/Body.Internal.cpp
- Fixed an issue that spawned `Strafe` aircraft on aircraft carriers may not be able to return normally if aircraft carriers moved a short distance when the aircraft is landing.
> [Phobos Fix] Fix `Strafe` spawnee may not be able to return normally since b43

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- src/Ext/Unit/Hooks.Harvester.cpp
- In vanilla, miners will remember their current location when they reach full load and move to that location after unloading. This makes miners to gradually move deeper into the mine and ignore the closer minerals.
- Now you can have the miner search for the nearest mineral again after unloading. If a closer mineral is found, the miner will go to that location instead of the previously recorded location.
```ini
[General]
HarvesterScanAfterUnload=false     ; boolean
[SOMEVEHICLE]
HarvesterScanAfterUnload=          ; boolean, default to [General] -> HarvesterScanAfterUnload
```
> [Dehardcode] Make harvesters do addtional scan after unload

- src/Ext/Bullet/Hooks.DetonateLogics.cpp
- src/Ext/Bullet/Hooks.cpp
- src/Ext/Script/Mission.Attack.cpp
- src/Ext/Techno/Body.Internal.cpp
- src/Ext/Techno/Body.Visuals.cpp
- src/Ext/Techno/Hooks.Firing.cpp
- src/Ext/Techno/Hooks.TargetEvaluation.cpp
- src/Ext/WarheadType/Body.cpp
- src/Ext/WarheadType/Body.h
- src/Ext/WarheadType/Detonate.cpp
- src/Utilities/GeneralUtils.cpp
- src/Utilities/GeneralUtils.h
currently there're several armor checks that haven't taken shield's armor into account, this pull request made a generic function for that
also made some simplification on Detonate.cpp during editing it, removing a seemingly redundant TechnoExt pointer which is always nullptr. Not sure if it'll accidentally break something tho, so review and test is needed
> [Minor] Shield armor fix

- CREDITS.md
- src/Ext/Bullet/Body.cpp
- src/Ext/Bullet/Body.h
- src/Ext/Bullet/Hooks.DetonateLogics.cpp
- src/Ext/Bullet/Hooks.Obstacles.cpp
- src/Ext/Bullet/Hooks.cpp
- src/Ext/Techno/Body.Internal.cpp
- src/Ext/Techno/Hooks.Airstrike.cpp
- src/Ext/VoxelAnim/Body.cpp
The previous `Arcing.AllowElevationInaccuracy` fix will make the projectile fall and detonate at different positions, which looks awkward in many times
This fix is based on https://github.com/Phobos-developers/Phobos/pull/269 and https://github.com/Phobos-developers/Phobos/pull/270, which will adjust the projectile's trace to make them fall and detonate at the same elevated position, also enabled by setting `Arcing.AllowElevationInaccuracy=false`.
Also includes some bullet optimizations from https://github.com/Phobos-developers/Phobos/pull/1568
> [Minor] Update on Arcing.AllowElevationInaccuracy

- docs/Fixed-or-Improved-Logics.md
- src/Ext/Unit/Hooks.Jumpjet.cpp
> [minor] Fix `OmniFire.TurnToTarget=true` not working when the unit is rearming

- src/Ext/Techno/Hooks.Transport.cpp
- src/Misc/Hooks.BugFixes.cpp
- In commit 0fc6584, the `Transporter` pointer of the techno was set to point to the bio reactor it is located in, but it was not correctly removed during reactor's selling mission or when reactor has destroyed by C4, resulting in a wild pointer.
> 在提交 0fc6584 中，`Transporter` 指针被设置为能够指向单位所处的生化反应炉，但它在反应炉被售卖或被 C4 摧毁时并未正确移除，导致了野指针。
- It is best to conduct specialized testing on the original repair content and `UnitAbsorb` related things.
> 最好对原修复内容以及 `UnitAbsorb` 再进行专项测试。
- Have not conducted a complete test yet, so I pull this request.
> 还未进行完整测试，所以提交了这个请求。
---
- Also fix a minor issue with `Size` calculation in `NoQueueUpToEnter`.
> 还修复了有关 `NoQueueUpToEnter` 中 `Size` 计算的问题。
- Replace the repair content in `InfantryEnterBuildingFix` with the same function used in other types.
> 将原本 …
> [Minor] Fix selling bio reactor crash in dev

- src/Ext/Sidebar/SWSidebar/SWColumnClass.cpp
- src/Ext/Sidebar/SWSidebar/SWColumnClass.h
- src/Ext/Sidebar/SWSidebar/SWSidebarClass.cpp
Currently, when attempting add a super weapon into sw sidebar, it will check if any button has same type of sw. If it exist, the attempt will be droped; Now it will add normally.
> [Minor] SWSidebar allows multiple additions of the same super weapon type

- docs/Fixed-or-Improved-Logics.md
- src/Ext/Anim/Hooks.cpp
- src/Ext/AnimType/Body.cpp
- src/Ext/AnimType/Body.h
previous `Damage.DealtByInvoker` doesn't really apply to anim warhead, this PR makes it inline with anim weapon. Notice that this might change the behavior of anim weapon and warhead a bit, but I think this should be the correct way. Any other feedbacks and reviews are welcome
`Damage.ApplyFirepowerMult` determines whether or not firepower modifiers from the animation's invoker are applied on the damage dealt from this animation, if exists
> [Minor] Damage.DealtByInvoker tweak & Damage.ApplyFIrepowerMult

- src/Ext/Techno/Body.Update.cpp
- src/Ext/Techno/Hooks.Firing.cpp
split from https://github.com/Phobos-developers/Phobos/pull/1568. This one is a bit controversial so I'd pull this alone for test and review
- instead of selecting weapon for every bullet, used the fixed value from `Interceptor.Weapon` once and for all
- added a RearmTimer check for the interceptor process
> [Minor] Optimize Interceptor

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Bullet/Hooks.DetonateLogics.cpp
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- src/Ext/WarheadType/Body.cpp
- src/Ext/WarheadType/Body.h
- src/Misc/Hooks.BugFixes.cpp
- Now, the original `DebrisMaximums` can be used in conjunction with new `DebrisMinimums` to limit the quantity of `DebrisTypes` when `DebrisTypes.Limit` is enabled.
- The default value of `DebrisTypes.Limit` is whether the number of `DebrisMaximums` is greater than (not equal to) 1 (for compatibility reasons).
```ini
[SOMETECHNO]        ; TechnoType
DebrisTypes.Limit=  ; boolean
DebrisMaximums=     ; List of integers
DebrisMinimums=     ; List of integers
[SOMEWARHEAD]       ; WarheadType
DebrisTypes.Limit=  ; boolean
DebrisMaximums=     ; List of integers
DebrisMinimums=     ; List of integers
```
```{hint}
How to generate `DebrisTypes` in the game:
- Generate the total number of debris through `MaxDebris` and `MinDebris` first.
- Traverse `DebrisTypes` and limit the …
```
> [Vanilla Enhancement] `DebrisMinimums`

- docs/New-or-Enhanced-Logics.md
- src/Ext/Rules/Body.cpp
- src/Ext/Rules/Body.h
- src/Ext/Techno/Hooks.ReceiveDamage.cpp
- Warheads are now able to define the extra damage multiplier for owner house, ally houses and enemy houses.
- `DamageOwnerMultiplier.NotAffectsEnemies` and `DamageAlliesMultiplier.NotAffectsEnemies` is used as the default value if `AffectsEnemies=false` is set on the warhead.
> Smart default value of `DamageAlliesMultiplier` and `DamageOwnerMultiplier`

- src/Ext/Techno/Hooks.cpp
Somehow, the vehicle called EnterIdleMode (probably in the functions of vehicle-related locomotors) in a move mission.
Then the megamission will be removed because the RefreshMegaMission function will only continue the megamission if the techno is in a guard mission.
> Fix vehicle with `AttackMove.StopWhenTargetAcquired` incorrectly lost megamission in some rare situation

- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Anim/Hooks.cpp
- src/Ext/AnimType/Body.cpp
- src/Ext/AnimType/Body.h
Replaces `UseCenterCoordsIfAttached` with new enum key with additional options for position customization. Will add rule to migration tool if/after this PR is merged.
--------------
- You can now customize position of attached animations via different values for `AttachedAnimPosition`.
- `default`: Animation shows up at the parent object's logical position (for buildings, this is the top-leftmost cell / cell #0).
- `center`: Animation shows up at the parent object's visual center.
- `ground`: Animation shows up at the parent object's visual center but forced to ground level. Note that the animations is still considered attached to the object and is likely to be drawn above objects that the object itself would cover unless other settings are used to compensate.
```ini …
```
> Improve attached animation position customization

- docs/New-or-Enhanced-Logics.md
- src/Ext/WeaponType/Body.cpp
- src/Ext/WeaponType/Body.h
- `KeepRange` controls how long the distance to maintain when the techno's ROF timer is ticking. What is actually read is its absolute value. If it is a positive value, it will be stayed outside this distance, just like it has a special `MinimumRange` after firing. If it is a negative value, it will be kept as close as possible to this distance, just like it has a special `Range` after firing. In addition, if the effective range section is too small, it will be considered unable to fire. It is best to have an effective range of 1.0, and 2.0 is best for Infantry.
- `KeepRange.AllowAI` controls whether this function is effective for computer.
- `KeepRange.AllowPlayer` controls whether this function is effective for human.
- The function won't take effect if the techno's rearm time left is …
> KeepRange.EarlyStopFrame

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Misc/Hooks.BugFixes.cpp
Fix the fact that when the selected unit is in a rearmed state, it can unconditionally use attack mouse on the target.
- 修正了当选定的单位处于重新武装状态时可以无条件对目标使用攻击鼠标的问题。
> [Minor] Fixed attack mouse action

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/Aircraft/Hooks.cpp
- src/Ext/Techno/Body.cpp
- src/Ext/Techno/Body.h
- src/Ext/Techno/Hooks.cpp
- src/Ext/TechnoType/Body.cpp
- src/Ext/TechnoType/Body.h
- src/Ext/Unit/Hooks.DisallowMoving.cpp
When `Speed=0` or the TechnoTypes cell cannot move due to `MovementRestrictedTo`, vehicles cannot attack targets beyond the weapon's range. `Area Guard` and `Hunt` missions will also become ineffective.
- `Speed=0`或`MovementRestrictedTo`导致单元格无法移动时载具无法攻击超出武器射程的目标。`区域守卫（AreaGuard）`和`猎杀（Hunt）`任务也会失效。
- When the vehicle loses its target, you can customize whether to align the turret direction with the vehicle body.
- When `Speed=0` or TechnoTypes cells cannot move due to `MovementRestrictedTo`, the default value is no; in other cases, it is yes.
- 当载具失去目标时可以自定义炮塔朝向和本体对齐。
- `Speed=0`或者`MovementRestrictedTo`导致单元格无法移动时默认值为no，其他情况为yes。
```ini
[SOMEVEHICLE]       ; VehicleType
TurretResponse=     ; boolean
```
> [Minor] Speed=0 extension

- CREDITS.md
- docs/New-or-Enhanced-Logics.md
- docs/Whats-New.md
- src/Ext/WarheadType/Body.cpp
- src/Ext/WarheadType/Body.h
- src/Ext/WarheadType/Detonate.cpp
- src/Utilities/AresAddressInit.cpp
- src/Utilities/AresFunctions.h
- Warheads can now uses the reverse-engineering logic *(Ares feature)* , the technology of the victim will be reversed.
```ini
[SOMEWARHEAD]          ; WarheadType
ReverseEngineer=false  ; boolean
```
```{warning}
This feature requires Ares 3.0 or higher to function!
```
> [Customized] Reverse engineer warhead

- src/Ext/Script/Mission.Attack.cpp
- src/Ext/Techno/Hooks.cpp
- src/Ext/Unit/Hooks.DisallowMoving.cpp
Team attack scripts no longer affect vehicles that cannot move and are beyond weapon range.
- 作战小队攻击脚本不再对无法移动且超出武器射程的载具生效。
> [Minor] Speed=0 extension 2

- docs/Whats-New.md
- src/Ext/Bullet/Body.cpp
- src/Ext/Bullet/Body.h
- src/Ext/Bullet/Hooks.cpp
- src/Ext/Rules/Body.cpp
- src/Ext/Scenario/Body.cpp
- src/Ext/Scenario/Body.h
- src/Ext/WarheadType/Body.cpp
- src/Ext/WeaponType/Body.cpp
- Reuse a special BulletClass instance for these detonations instead of always creating a new one.
- Fix a bug that causes the detonation coords to snap to the logical target - this is not always desirable and should be handled separately where needed by making sure the detonation coords are same as target coords.
> Improve/optimize arbitrary weapon/warhead detonation code

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Ext/Aircraft/Hooks.cpp
- src/Ext/Building/Hooks.cpp
- src/Ext/Techno/Body.Update.cpp
- src/Ext/Techno/Hooks.Transport.cpp
- Units' `LaserTrails` will no longer lags behind by one frame.
> 单位的 `LaserTrails` 将不再延迟在单位后面一帧。
- Units' `LaserTrails` will no longer be lost when they're transformed from ones without `LaserTrails` into ones with `LaserTrails`.
> 单位的 `LaserTrails` 将不再会在从无 `LaserTrails` 到有 `LaserTrails` 的变形时丢失。
- The transformed units can be reset to the correct `FireAngle` and `TurretRecoil`.
> 单位变形后能够正确重置到正确的 `FireAngle` 和 `TurretRecoil` 。
> [Minor] Fix several issues

- CREDITS.md
- docs/Fixed-or-Improved-Logics.md
- docs/Whats-New.md
- src/Misc/Hooks.BugFixes.cpp
> Fixed an issue that the jumpjet vehicles cannot stop correctly after going berserk
