src/Commands/ObjectInfo.h

Related to issue #53
Some changes:
- I left one space between some values and the "(" (Cosmetic change).
- Changed the first owner value by the Country House ID.
- I changed the Script line to look a bit more like the ones in AImd.ini (line number = 1º arg, 2º arg) and in case of line -1 hide those unnecessary variables.
- Multiplied by 4 the message duration, from 150 frames to 600.

Small changes

---

Phobos.vcxproj
src/Ext/Bullet/Body.cpp
src/Ext/Bullet/Body.h
src/Ext/BulletType/Body.cpp
src/Ext/BulletType/Body.h
src/Ext/Techno/Body.cpp
src/Ext/Techno/Body.h
src/Ext/TechnoType/Body.cpp
src/Ext/TechnoType/Body.h
src/Ext/TechnoType/Hook.cpp
src/Ext/WeaponType/Hooks.cpp

```ini
[Unit]
Interceptor= [bool]
Interceptor.GuardRange= [double]
Interceptor.EliteGuardRange= [double]
[Projectile]
Interceptable= [bool]
```
*Intercepter's weapon must have a projectile with `Inviso=yes`
thanks to ChrisLv-CN, logic is inspired by him

Added Intercepter Logic

---

src/Commands/ObjectInfo.h

Added Passengers / Occupants ID's line when units enter into transports / garrisonable structures.

New printed info

---

docs/New-or-Enhanced-Logics.md
src/Ext/TechnoType/Body.cpp
src/Ext/TechnoType/Body.h
src/Ext/WarheadType/Body.cpp
src/Ext/WarheadType/Body.h
src/Ext/WarheadType/Detonate.cpp

```ini
[WarheadType]
Crit.Chance= (float, def 0.0); chance
Crit.Damage= (integer, def 0); extra damage
Crit.Affects= (same as SWType's, def "all")
Crit.Spread= (float, def CellSpread); change to this cellspread
Crit.Anim= (list of animation); random play or just play 1
[TechnoType]
ImmuneToCrit= (bool, def no); immune to this feature
```
Closes #75.
Used some Ares 0.a codes

First version of Critical Hit on warhead

---

README.md
docs/Fixed-or-Improved-Logics.md
src/Ext/TechnoType/Body.h
src/Ext/TechnoType/Hooks.VehicleToBuildingMCFix.cpp

Also tested the undeploy anim and if the player explodes when the original owner of the MC unit died.

Fixed anim bug when deploying into structure

---

README.md
docs/New-or-Enhanced-Logics.md
src/Ext/Script/Body.cpp
src/Ext/Script/Body.h

Action 73,0 was created in mind for Aircrafts but could be used in other scenarios. It prevents a very rare bug that makes the AI aircraft going up & down in loop in the helipad.
Example of use:
[B0001066-G]
Name=Load and attack sructures in loop
0=73,0
1=0,2
2=6,1

Script 73 Wait until full ammo

---

docs/Fixed-or-Improved-Logics.md
src/Ext/TerrainType/Body.cpp
src/Ext/TerrainType/Body.h
src/Ext/TerrainType/Hooks.cpp

Accepts either one value or a range (lower bound, higher bound, inclusive)
```
SpawnsTiberium.GrowthStage=3
```

Implement SpawnsTiberium.GrowthStage

---

src/Commands/ObjectInfo.h
src/Misc/Shield.cpp
src/Misc/Shield.h

If those values exist they will appear.

Added Shield HP and Ammo in ObjectInfo

---

Phobos.vcxproj
README.md
docs/Fixed-or-Improved-Logics.md
src/Ext/WeaponType/Body.cpp
src/Ext/WeaponType/Body.h
src/Ext/WeaponType/Hook.EBolt.cpp

Allow user to Disable spesific bolt from ElectricBolt Weapon
```
[SOMEWEAPONTYPE]       ; WeaponType
IsElectricBolt=true   ;an ElectricBolt Weapon
Bolt.Disable1=false ; boolean, Disable bolt Number 1
Bolt.Disable2=false ; boolean, Disable bolt Number 2
Bolt.Disable3=false ; boolean, Disable bolt Number 3
```

Allow user to Disable spesific bolt from ElectricBolt Weapon

---

src/Ext/RadSite/Body.cpp

Fix for latest issue reported on discord for B11 :
https://ptb.discord.com/channels/338055131666972683/773636942775582720/831188276915339315
Fixed Gif :
https://i.imgur.com/8DsCyeW.gif

Fix CellSetRadSite

---

docs/Fixed-or-Improved-Logics.md
src/Ext/TerrainType/Body.cpp
src/Ext/TerrainType/Body.h
src/Ext/TerrainType/Hooks.cpp
src/Utilities/GeneralUtils.cpp
src/Utilities/GeneralUtils.h

```ini
SpawnsTiberium.CellsPerAnim=1
```

Customizable amount of ore cells spawned per animation

---

Phobos.vcxproj
docs/Fixed-or-Improved-Logics.md
src/Ext/Aircraft/Body.cpp
src/Ext/Rules/Body.cpp
src/Ext/Rules/Body.h
src/Ext/Scenario/Body.cpp
src/Ext/Scenario/Body.h
src/Ext/Scenario/Hooks.Waypoints.cpp
src/Ext/Scenario/Hooks.cpp
src/Phobos.Ext.cpp
src/Utilities/SavegameDef.h

In vanilla YR, this number is limited to [0, 701], this PR will remove that limitation.
~~Who will use all 702 waypoints?~~

Remove the limitation of Waypoint

---

README.md
docs/Fixed-or-Improved-Logics.md
docs/Whats-New.md
src/Misc/Hooks.BugFixes.cpp

Building placement hotkey not responding

---

docs/Fixed-or-Improved-Logics.md
docs/Whats-New.md
src/Misc/Hooks.BugFixes.cpp

Undeploy building into a unit plays EVA_NewRallyPointEstablished

---

docs/New-or-Enhanced-Logics.md
docs/Whats-New.md
src/Ext/Techno/Hooks.cpp
src/Ext/TechnoType/Body.cpp
src/Ext/TechnoType/Body.h

implement InitialStrength

---

docs/New-or-Enhanced-Logics.md
docs/Whats-New.md
src/Ext/BuildingType/Hooks.Upgrade.cpp

PowersUp interaction with Ares

---

Phobos.vcxproj
docs/Fixed-or-Improved-Logics.md
docs/Whats-New.md
docs/locale/zh_CN/LC_MESSAGES/Fixed-or-Improved-Logics.po
docs/locale/zh_CN/LC_MESSAGES/Whats-New.po
src/Ext/Scenario/Body.cpp
src/Ext/Scenario/Body.h
src/Ext/Scenario/Hooks.LocalVariables.cpp
src/Ext/Scenario/Hooks.Variables.cpp
src/Ext/Scenario/Hooks.Waypoints.cpp

In vanilla YR, local variables are limited up to 100, now you can use up to INT_MAX waypoints.

Unlimited Variables

---

docs/New-or-Enhanced-Logics.md
docs/Whats-New.md

Some documentation lines of the script action 112 are missing.

fix some docs regarding script action 112

---

docs/New-or-Enhanced-Logics.md
docs/Whats-New.md
src/Ext/Script/Body.cpp
src/Ext/Script/Body.h
src/Ext/TAction/Body.cpp
src/Ext/TAction/Body.h
src/Ext/TEvent/Body.cpp
src/Ext/TEvent/Body.h
src/Ext/TEvent/Hooks.cpp
src/Ext/Trigger/Hooks.cpp

Allow the variables to be edited by another variable

Numeric variables part 2

---

Phobos.vcxproj
README.md
docs/Fixed-or-Improved-Logics.md
docs/Whats-New.md
src/Ext/Building/Body.cpp
src/Ext/Building/Body.h
src/Ext/BuildingType/Body.cpp
src/Ext/BuildingType/Body.h
src/Ext/Techno/Hooks.Grinding.cpp

You can now customize which types of objects a building with `Grinding` set can grind as well as the grinding sound.
- `Grinding.AllowAllies` changes whether or not to allow units to enter allies' buildings.
- `Grinding.AllowOwner` changes whether or not to allow units to enter your own buildings.
- `Grinding.AllowTypes` can be used to define InfantryTypes and VehicleTypes that can be grinded by the building. Listing any will disable grinding for all types except those listed.
- `Grinding.DisallowTypes` can be used to exclude InfantryTypes or VehicleTypes from being able to enter the grinder building.
- `Grinding.Sound` is a sound played by when object is grinded by the building. If not set, defaults to `[AudioVisual]`->`EnterGrinderSound`.
- `Grinding.Weapon` is a weapon fired at the …

Grinder improvements / additions

---

docs/New-or-Enhanced-Logics.md

I wrote:
ForceWeapon.Naval.Decloacked
instead of:
ForceWeapon.Naval.Decloaked

Small documentation fix

---

src/Misc/CaptureManager.cpp

Units retaining orders after changing ownership bugfix

---

docs/locale/zh_CN/LC_MESSAGES/New-or-Enhanced-Logics.po

Change it to the right one in English version.

Wrong picture in Chinese version document（中文版文档图片错了）

---

CREDITS.md
Phobos.vcxproj
docs/Fixed-or-Improved-Logics.md
docs/Whats-New.md
src/Ext/Techno/Hooks.VehicleToBuildingMCFix.cpp
src/Ext/Unit/Hooks.Jumpjet.cpp

Fix turreted jumpjet units always facing bottom-right direction when stop firing

---

src/Ext/Bullet/Hooks.cpp
src/Ext/Rules/Body.cpp
src/Ext/Rules/Body.h
src/Ext/TechnoType/Body.cpp

hot fix bullet type insertion for 3bf6c5e
Use DVC for HarvesterTypes

[Hotfix] 3bf6c5e and c72b14a

---

src/Misc/Hooks.Image.cpp

Responding to a report on Mod Haven Discord server.

[Minor] Hotfix Image swapping when loading a savefile

---

CREDITS.md
docs/Fixed-or-Improved-Logics.md
docs/Whats-New.md
src/Ext/Anim/Hooks.cpp

Use `CustomPalette` for anim with `Tiled=yes`

---

CREDITS.md
Phobos.vcxproj
docs/AI-Scripting-and-Mapping.md
docs/Whats-New.md
src/Ext/House/Hooks.cpp
src/Ext/Team/Hooks.cpp

Aims to fix #778 
InitialPayload logic won't work.
Needs testing.

Fix teams spawned by trigger action 7,80,107 cannot use IFV or opentopped logic

---

src/Utilities/TemplateDef.h

As we know, std::vector<bool> save boolean values as bits.

[Minor] Specialization `Save`/`Load` Function of `ValueableVector`

---

src/Ext/Script/Body.cpp
src/Ext/Techno/Body.cpp
src/Ext/Techno/Body.h

And tweaks the AI air transport behavior when infantry selects the transport.

Fixes random crashes in some AI script actions

---

CREDITS.md
docs/New-or-Enhanced-Logics.md
docs/Whats-New.md
src/Ext/WarheadType/Detonate.cpp
src/New/Type/ShieldTypeClass.cpp
src/New/Type/ShieldTypeClass.h

```ini
[SOMESHIELD]
ImmuneToCrit = no
```

Allow `ImmuneToCrit` for shields

---

CREDITS.md
docs/Fixed-or-Improved-Logics.md
docs/Whats-New.md
src/Ext/TechnoType/Body.cpp
src/Ext/TechnoType/Body.h
src/Ext/Unit/Hooks.Jumpjet.cpp

Allow jumpjet to crash without rotation

---

CREDITS.md
docs/Fixed-or-Improved-Logics.md
docs/Whats-New.md
src/Ext/CaptureManager/Hooks.cpp

Break the mind-control link when capturing a mind-controlled building with an engineer

---

Phobos.vcxproj
src/Ext/Bullet/Body.cpp
src/Ext/Techno/Body.cpp
src/Ext/Techno/Hooks.Firing.cpp
src/Ext/TechnoType/Body.cpp
src/Ext/TechnoType/Body.h
src/Ext/WarheadType/Detonate.cpp
src/New/Type/Affiliated/InterceptorTypeClass.cpp
src/New/Type/Affiliated/InterceptorTypeClass.h

As Trsdy's commet of #726
> I didn't manage to give my review on this in time. Basically you give too many new arguments on this specific feature, which makes the code looks _extrêmement lourde_, in this case I would rather suggest you guys wrap those into a new entity, like the AttachEffectType or PrismForwarding in Ares, and see if it can work like an AttachEffect. Moreover, it looks like a standalone trigger-action system already, so maybe not just limited to self-destruction.
> 
> Same suggestion for other similar tags like the interceptor one> I didn't manage to give my review on this in time. Basically you give too many new arguments on this specific feature, which makes the code looks _extrêmement lourde_, in this case I would rather suggest you guys wrap those into a new entity, …

[Minor] InterceptorType

---

CREDITS.md
docs/Fixed-or-Improved-Logics.md
docs/Whats-New.md
src/Ext/Techno/Hooks.Firing.cpp
src/Ext/TechnoType/Body.cpp
src/Ext/TechnoType/Body.h

`AlternateFLH` can have more than five.

Additional `AlternateFLH` entries beyond five

---

src/Ext/Rules/Hooks.INIClass.cpp
src/Misc/Hooks.INIInheritance.cpp
src/Utilities/TemplateDef.h

Booleans, floating point numbers, number pairs, and locomotors will now be inherited properly.

[Minor] Fix incomplete inheritance for some value types

---

CREDITS.md
Phobos.vcxproj
docs/Whats-New.md
src/Commands/FrameByFrame.cpp
src/Ext/Techno/Body.Update.cpp
src/Ext/Techno/Body.cpp
src/Ext/WarheadType/Body.cpp
src/Ext/WarheadType/Body.h
src/Ext/WarheadType/Detonate.cpp
src/Locomotion/TestLocomotionClass.cpp
src/Locomotion/TestLocomotionClass.h
src/Misc/Hooks.BugFixes.cpp
src/Phobos.COM.cpp
src/Phobos.COM.h
src/Utilities/TemplateDef.h

New locomotor code is `{74FC2B59-C2D3-47D7-9D10-93436A34EBB9}`.
Reviews in progress are welcome.

Custom locomotor example implementation

---

CREDITS.md
docs/Fixed-or-Improved-Logics.md
docs/New-or-Enhanced-Logics.md
docs/Whats-New.md
src/Ext/Rules/Body.cpp
src/Ext/Rules/Body.h
src/Ext/TechnoType/Body.cpp
src/Ext/TechnoType/Body.h
src/Ext/TechnoType/Hooks.cpp

vxl turret shadow

---

CREDITS.md
docs/User-Interface.md
docs/Whats-New.md
src/Misc/Hooks.BugFixes.cpp

Essence of the issue:
After fix:

Fixed position and layer of info tip and reveal production cameo on selected building

---

src/Ext/Unit/Hooks.Jumpjet.cpp

@mevitar could you plz make some regression tests on this? Apart from testing if it fixes your issue, but also tests if it doesn't break anything
Fix issue #1216

Fix issue #1216

---

src/Ext/Anim/Body.cpp
src/Misc/Hooks.VeinholeMonster.cpp

- Make some hooks in veinhole code have return 0
- Remove accidental cast into nowhere

Refactor hooks in veinhole code

---

src/New/Type/DigitalDisplayTypeClass.cpp

[Minor] Fix bug with center alignment and negative spacing in `DigitalDisplay`

---

CREDITS.md
docs/Fixed-or-Improved-Logics.md
docs/Whats-New.md
src/Misc/Hooks.BugFixes.cpp

Disguised unit can use correct palette that if target has custom palette

---

CREDITS.md
docs/Fixed-or-Improved-Logics.md
docs/Whats-New.md
src/Misc/Hooks.BugFixes.cpp

[BugFix]Tunnel/Walk/Mech locomotor being stuck when moving too fast bugfix

---

src/Misc/PhobosToolTip.cpp

[Minor] Make tooltips background effects not only work in sidebar

---

src/Ext/TAction/Body.cpp
src/Ext/TEvent/Body.cpp

The reason for this was explained in #1425 . Now alll new events & actions use country index, aligning with vanilla customs.

[Minor] Use country index for all events and actions

---

src/Ext/Techno/Hooks.Firing.cpp

[Minor] Fix develop branch's `DiskLaser=yes` error

---

docs/Fixed-or-Improved-Logics.md
src/Misc/Hooks.BugFixes.cpp

As the title says, a vanilla fix.

[Minor] Fix technos unable to stop the area guard mission

---

CREDITS.md
docs/Whats-New.md

ststl omitted some acknowledgments.
After communicating and confirming with him and other contributors who were with us at the time and are still reachable, he indicated that he is currently busy and also unable to directly modify the file, so he asked me to initiate this PR to complete it.
just all.

Some Omitted Credits

---

docs/User-Interface.md

Fix invalid document links

---

docs/AI-Scripting-and-Mapping.md
docs/Fixed-or-Improved-Logics.md
docs/Miscellanous.md
docs/New-or-Enhanced-Logics.md
docs/User-Interface.md
docs/Whats-New.md

- Correct formatting issues such as spaces and newlines.
- Correct two incomplete links.
- Correct the mismatch between the content and version in the contribution document.

[Minor] Fix Doc

---

docs/requirements.txt
src/Ext/Building/Hooks.cpp
src/Ext/Sidebar/Body.cpp

If enable the building production queue, when a building is fully completed, the remaining buildings will be turned into gray cameo as before.

[Minor] Notify the completed building in building production queue

---

src/Ext/Aircraft/Hooks.cpp

This PR should improve behaviour of aircraft when assigned area guard mission (`G` on keyboard or the guard button in advanced command bar) with `[General]` -> `ExtendedAircraftMissions=true`, particularly when landed on a dock. Before, aircraft would take off from the dock even if there was no ammo, no targets nearby etc. Now they will only take off if they have a target to engage.
Some notes:
- Repeatedly assigning area guard on docked aircraft that have partially loaded ammo will stall the reloading process even if the jet won't take off. The same was true before, just more obvious (and longer duration) with the aircraft actually taking off. This is no longer true for aircraft with no ammo at all, however.
- Area guard on aircraft is still not persistent (e.g doesn't expire without …

Improve aircraft area guard behaviour

---

CREDITS.md
docs/Fixed-or-Improved-Logics.md
docs/Whats-New.md
src/Ext/Bullet/Hooks.cpp
src/Ext/BulletType/Body.cpp
src/Ext/BulletType/Body.h

`BombParachute` deglobalization

---

src/Ext/Building/Hooks.cpp

the issue is introduced by https://github.com/Phobos-developers/Phobos/pull/1588. This fix might fix it but need testing

[Minor] Fix building anims being removed after Chronoshift

---

src/Ext/Techno/Body.Update.cpp
src/Ext/TechnoType/Body.cpp
src/Ext/TechnoType/Body.h
src/Ext/WarheadType/Detonate.cpp
src/New/Entity/ShieldClass.cpp

It seems that adding a NONE_STR shield is redundant, but not sure if removing it will result in any problem. Made a PR for testing first

[Minor] Remove NONE_STR shield
